### ISSUE TITLE
Unable to install with drush

### ISSUE THREAD

**Issue by sandetsky** [linnovate/openideal#110]
I have try to install OpenIdeaL with drush and get

Unable to clone bootstrap_panels_horizontal_tabs from http://git.drupal.org/sandbox/ShaunDychko/2126611.git.                  [error]

How I can to fix it?

**Comment by zohar** [comment]
What is the drush command you are running?

**Comment by sandetsky** [comment]
drush  make build-openideal-github.make /root/make/drup-idea

**Comment by zohar** [comment]
Can you please paste the output of `git remote -v` in your local repository and the content of `build-openideal-github.make` ?

**Comment by zohar** [comment]
I just hit the same problem. This should be a problem in one of the dependencies and not in OpenideaL. I'll check.

**Comment by sandetsky** [comment]
[root@localhost openideal]# git remote -v
origin  https://github.com/linnovate/openideal.git (fetch)
origin  https://github.com/linnovate/openideal.git (push)


[root@localhost openideal]# cat build-openideal-github.make
api = 2
core = 7.x
projects[] = drupal
projects[idea][type] = profile
projects[idea][download][type] = git
projects[idea][download][url] = https://github.com/linnovate/openideal.git
projects[idea][download][branch] = 7.x-4.x

**Comment by sandetsky** [comment]
Thank you. Waiting for further info

**Comment by zohar** [comment]
Problem should be solved now. See https://github.com/linnovate/openideal/commit/bbdba301c71b64bb5afa980c2d555d0de65201b6

Please report back if it works for you as well and reopen if problem persists.

Thank you for reporting this bug!
