### ISSUE TITLE
'Back' and 'Submit your idea' buttons

### ISSUE THREAD

**Issue by sandetsky** [linnovate/openideal#113]
'Back' and 'Submit your idea' buttons on the page ?q=node/add/idea looks like '<span>Back</span>' and '<span>Submit your idea</span>'
![Screenshot_1](https://user-images.githubusercontent.com/49277861/55604591-14442d00-5760-11e9-8e2a-e4077729b18a.jpg)

**Comment by zohar** [comment]
We noticed this problem only when admin is logged in. I'll accept patches to correct this but since it's only admin it's a low priority for us.
