### ISSUE TITLE
Updates? 

### ISSUE THREAD

**Issue by danjng** [linnovate/openideal#114]
I'd love to see this continue with development. Any intention to update to work on newer versions of drupal and php and mysql? 

I've build a docker container and the only way i was able to get this to work was to use php 5.6 and mysql 5.x and drupal 7.67...

Thoughts?

**Comment by liorkesos** [comment]
First of all we'd be happy to collaborate and review your docker deployment as part of the project.
Upgrading to Drupal 8!is a substantial effort and were looking for an organization willing to sponsor the migration...

**Comment by danjng** [comment]
Agreed... Upgrading to Drupal 8 is probably going to be pretty labor intensive... If I can help in the future, I'll try to - I don't know a lot about developing on top of the Drupal platform though. I think it's nice that this is offered as open source especially if it has features shared with a lot of other paid products. 

Anyhow, I've published the code for creating containers for this. You can find it here: https://github.com/danjng/openideal-docker 

That code is completely independent right now, but can eventually be merged (if that's the direction of this project). It's probably OK to keep it separate right now since it does have separate dependencies (Drupal, compose, drush, etc.) in order to run. I'll close this issue and we can re-open/continue this conversation as needed. 

Thank you for your contributions!

**Comment by heyyo-droid** [comment]
We prefer to propose official Drupal images
https://github.com/linnovate/openideal/wiki/Install-OpenideaL-with-Docker4Drupal-by-Wodby
