### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by Artmir** [linnovate/openideal#118]
The command:
`composer create-project linnovate/openideal_project`
Gives the following error:

`[InvalidArgumentException]
  Could not find package linnovate/openideal_project with stability stable.`

**Comment by zohar** [comment]
True. 
I am creating a 2nd repository for the above to work. It will pull in drupal core + openideal distribution.

**Comment by Artmir** [comment]
I was just doing that also :). 
I resolved most of the issues which had to do with php limits and library paths. I ran the install.php script via browser and it goes up to 100%, right after that it throws the following, which I am still scratching my head with why it is happening:

The required CKEditor plugs are missing. To install the CKEditor plugins run drupal ckeditor_media_embed:install if you have Drupal Console installed. Otherwise, please see the installation instructions on the page for additional install methods. 

The website encountered an unexpected error. Please try again later.

```
Drupal\Core\Config\UnmetDependenciesException:` Configuration objects provided by <em class="placeholder">idea</em> have unmet dependencies: <em class="placeholder">language.content_settings.block_content.basic (content_translation, language), language.content_settings.contact_message.feedback (language)</em> in Drupal\Core\Config\UnmetDependenciesException::create() (line 98 of core\lib\Drupal\Core\Config\UnmetDependenciesException.php).

Drupal\Core\Config\UnmetDependenciesException::create('idea', Array) (Line: 509)
Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'idea') (Line: 132)
Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'idea') (Line: 161)
Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1649)
install_install_profile(Array) (Line: 695)
install_run_task(Array, Array) (Line: 570)
install_run_tasks(Array, NULL) (Line: 118)
install_drupal(Object) (Line: 44)
```

**Comment by zohar** [comment]
@Artmir please try `composer create-project linnovate/openideal-composer` and report back.
If all goes well you should find a `openideal-composer` directory with a full Drupal installation (under the `openideal-composer/web` directory). OpenideaL itself should be installed under `openideal-composer/web/profiles/contrib/idea`.

**Comment by zohar** [comment]
OK cool.

**Comment by zohar** [comment]
Please run `drush cr` and see if it helps.

> 
> The website encountered an unexpected error. Please try again later.
> 
> ```
> Drupal\Core\Config\UnmetDependenciesException:` Configuration objects provided by <em class="placeholder">idea</em> have unmet dependencies: <em class="placeholder">language.content_settings.block_content.basic (content_translation, language), language.content_settings.contact_message.feedback (language)</em> in Drupal\Core\Config\UnmetDependenciesException::create() (line 98 of core\lib\Drupal\Core\Config\UnmetDependenciesException.php).
> 
> Drupal\Core\Config\UnmetDependenciesException::create('idea', Array) (Line: 509)
> Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'idea') (Line: 132)
> Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'idea') (Line: 161)
> Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
> Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1649)
> install_install_profile(Array) (Line: 695)
> install_run_task(Array, Array) (Line: 570)
> install_run_tasks(Array, NULL) (Line: 118)
> install_drupal(Object) (Line: 44)
> ```

**Comment by Artmir** [comment]
Thanks Zohar,
I will try the new repo and report back.

**Comment by Artmir** [comment]
Managed to install up to 100% again. The repository was fetched without errors using: `composer create-project linnovate/openideal-composer`

This time it got hung on the last step and didn't finalize; eventually running out of max-exeution time
`Fatal error: Maximum execution time of 512 seconds exceeded in B:\xampp\htdocs\MY_PROJECT\web\core\lib\Drupal\Core\Database\Statement.php on line 59`

**Comment by zohar** [comment]
@Artmir On my local machine I have a similar problem, so I run it like this:
`COMPOSER_MEMORY_LIMIT=-1 composer create-project linnovate/openideal-composer`

**Comment by zohar** [comment]
- drush site-install works without any issues (as oppose to browser based installation).
- after the installation I had to run `drush cr` for the rules to kick in.

**Comment by zohar** [comment]
@Artmir what php version do you have (both cli and local server)?

**Comment by Artmir** [comment]
I am using Drush10 with Composer on windows 10. PHP has come together with the XAMPP installation. 
PHP 7.4.5 (cli) (built: Apr 14 2020 16:17:34) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group Zend Engine v3.4.0, Copyright (c) Zend Technologies with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies.
For some reason I am suspecting maybe Drush version is not compatible... I have exhausted all ideas currently. 

I can also try with ubuntu  virtual server later to see if that works.

**Comment by Artmir** [comment]
Updated php and mysql to latest release. Installed composer and drush 9. When I try drush site-install OpenideaL, all sorts of issues happen and doesn't continue past connection with mysql.

When I use only drush site-install. It proceeds smoothly and installs only the normal drupal installation. (Not the OpenideaL profile). 

Same issue when tried with Ununtu 20.x as well.

**Comment by zohar** [comment]
I confirm that drush installation works perfect on my side. PHP 7.4 on Mac OS. 
I'm going to push a new version. Let's try again.

**Comment by Artmir** [comment]
From which directory are you running the drush command and are you specifying the profile installation in the command? 

I am using the drush commands as described here: https://drushcommands.com/drush-9x/site/site:install/. When it comes to the profile selection I just write: OpenideaL.

**Comment by zohar** [comment]
Just updated the code. Please try again.
I run my drush command from within the web folder:

`drush si -y --account-name some_user --account-pass some_pass --account-mail my_mail@mydomain --site-name "Local OpenideaL" --db-url=mysql://user@127.0.0.1/db_name idea`

- change `some_user` with your username
- change `some_pass` with your password
- change `my_mail@mydomain` with your email address
- change `user@127.0.0.1/db_name` with your DB settings
- the last bit - `idea` is the name of the profile (as it is the machine name of the project in Drupal.org, while OpenideaL is the name of the "product")

**Comment by Artmir** [comment]
Damn! I got the name of the profile wrong it seems. My daughter is now going asleep and can't really make any noise right now or it will be a long night 😂. I will give it a go first thing in the morning.

**Comment by zohar** [comment]
Just don't shout! ;-)

**Comment by Artmir** [comment]
> 
> 
> Just don't shout! ;-)

Haha, I have this loud mechanical keyboard, every time I so much touch it, she wakes up!
I just ran the install now and I can confirm that it is working. It was the name of the profile that messed up the installation! Thanks for clarifying also the install steps, that's really helpful!!
