### ISSUE TITLE
Override user image field

### ISSUE THREAD

**Issue by nevos** [linnovate/openideal#12]
when a user image is broken, override with a default avatar, 
do it on a field template level

**Comment by israeldahan** [comment]
change the fetures user activity. 

[change_the_src_image_on_messege_type_new_user.patch.tar.gz](https://github.com/linnovate/openideal/files/1347086/change_the_src_image_on_messege_type_new_user.patch.tar.gz)

**Comment by zohar** [comment]
@israel123 you should also take care of other message types in this feature

**Comment by israeldahan** [comment]
[change_src_img_on_message_new_comment.patch.tar.gz](https://github.com/linnovate/openideal/files/1347126/change_src_img_on_message_new_comment.patch.tar.gz)
אוקיי, לא שמתי לב היה עוד פיצ'ר אחד עם תמונה
הנה הפאצ' שלו.

**Comment by israeldahan** [comment]
[github_12_images_default.patch.tar.gz](https://github.com/linnovate/openideal/files/1348345/github_12_images_default.patch.tar.gz)

**Comment by israeldahan** [comment]
[github-12-images-default.patch.tar.gz](https://github.com/linnovate/openideal/files/1348370/github-12-images-default.patch.tar.gz)
