### ISSUE TITLE
Install OpenIdeal

### ISSUE THREAD

**Issue by zoheirop** [linnovate/openideal#124]
Hello everybody,

I am not an expert on web development, but i did not find any documentation or guide of Implementation og this solution!

 Please if anyone could help me, i need the steps to install OpenIdeal

best Regards

**Comment by zohar** [comment]
@zoheirop Hi, the instructions are on the readme file: https://github.com/linnovate/openideal/blob/3.x/README.md

**Comment by zoheirop** [comment]
THANK YOU
