### ISSUE TITLE
Problem with install drush bootstraphook

### ISSUE THREAD

**Issue by zoheirop** [linnovate/openideal#125]
<img width="945" alt="drush issue after installation" src="https://user-images.githubusercontent.com/9295687/95474467-08e94780-097d-11eb-85e7-7b06f824ee3c.PNG">

help please !!

**Comment by zohar** [comment]
I have no experience on Windows machines.
Did the `composer install` pass without any problems?

**Comment by zoheirop** [comment]
yes without any problems :/
