### ISSUE TITLE
openideal installation ajax issue

### ISSUE THREAD

**Issue by zoheirop** [linnovate/openideal#126]
<img width="556" alt="AJAX ISSUE" src="https://user-images.githubusercontent.com/9295687/95519583-47065b80-09bd-11eb-866d-df0c24b3228d.PNG">

anyone have a solution for this problem please !!

**Comment by zohar** [comment]
@zoheirop please wait for the next stable release (today/tomorrow) and test again.

**Comment by zoheirop** [comment]
okay !
thanks a lot

**Comment by Artmir** [comment]
Can you tell what server are you using and also versions?

**Comment by zohar** [comment]
I just published a new release. Give it a few minutes to update on Packagist and try again.

**Comment by elrond1337** [comment]
![2021-01-05_19h31_24](https://user-images.githubusercontent.com/40789651/103684942-aa883100-4f8c-11eb-907b-88493d632ec2.png)
@zoheirop @Artmir how did you manage to solve this problem?

**Comment by Artmir** [comment]
Tell some more info what you are using. 
Myself I installed using GitBash via command line on Centos. I haven't tried the web browser version. Check the documentation, I think it is quite easy to follow how to install. Also increase php memory limits just in case.

**Comment by elrond1337** [comment]
I tried to install via Web GUI using xampp on Windows to simulate Apache and mysql and increased memory Limit up to 512 Mb in php.ini config and Also the other recommended change like increasing timeout etc.

**Comment by Artmir** [comment]
Here is what you can do as an alternative. 
-Get Git for your desktop computer. 
-Install Composer and drush packages.
-if you are running F-secure turn it off as it will crash the installation with a false positive.
-Open Git and navigate to your destination folder (usually in htdocs) 
-Follow the installation instructions from the main page.

**Comment by zohar** [comment]
The easiest is to use `composer create-project linnovate/openideal-composer` as described on the project's readme.

**Comment by heyyo-droid** [comment]
Please reopen if it's still an issue
