### ISSUE TITLE
Update documentation 

### ISSUE THREAD

**Issue by Artmir** [linnovate/openideal#132]
This is not an issue but it would be great to know how OpenideaL can be updated to reflect latest changes in repository.

**Comment by zohar** [comment]
It certainly is an issue :-|
Are you talking of something like a Changelog?

**Comment by Artmir** [comment]
Yes. :) Something that would pull latest changes from Git. For example there were some changes recently in composer.json css and a bunch of other files. It would be great to run a composer update to fetch latest updates from repository.

**Comment by zohar** [comment]
These are two different things. 
After code is updated, you should be able to run `git pull` and `composer update` to update your code (I think you should remove `composer.lock` for that. ( @db-Matroskeen ?)
But I thought you were talking about a verbal description of what has changed.

**Comment by Artmir** [comment]
For me it says delete composer.json, gitignore and readme. Testing on local-dev. 
(Edit) Nope that broke it. Reverting..

**Comment by db-Matroskeen** [comment]
In the normal mode, once the new release is available, we are able to do `composer update linnovate/openideal`. It supposed to pull the latest changes. (removing files isn't necessary)

In development mode (using the latest dev version), we can go into the profile directory (`web/profiles/contrib/idea`) and do the git pull. After that, configuration files should be imported manually (see: https://github.com/linnovate/openideal-composer#configuration-management).

**Comment by Artmir** [comment]
Thanks for the clarification @db-Matroskeen! @zohar I think it would be great to add this info to the install documentation.

**Comment by zohar** [comment]
@Artmir sounds like an excellent opportunity for a first contribution :-)

**Comment by Artmir** [comment]
It is my pleasure to contribute back. With some help how to push changes, I would be happy to do it. Similarly any other changes I make to my development version, I would be happy to contribute here.

**Comment by zohar** [comment]
Cool! 
In github you can Fork the project, change whatever you want, and then create a Pull Request to the original project.
See https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by fogsag** [comment]
Maybe this process is similar and can be adopted to openideal?: https://github.com/acquia/lightning/wiki/Update-Instructions

**Comment by heyyo-droid** [comment]
feel free to reopen if still an issue
