### ISSUE TITLE
Install Issue: Using drush or manual module install

### ISSUE THREAD

**Issue by ibwo88** [linnovate/openideal#133]
Hi, not able to install with drush or manual install with web GUI.
Environment:
Drupal 8.9.7
php 7.4
MySQL 5.7
Centos 8

Error message:

[notice] Performed install task: install_bootstrap_full
 [error]  Error: Class 'Drupal\content_moderation\Event\ContentModerationEvents' not found in Drupal\openideal_idea\EventSubscriber\OpenidealIdeaEventSubscriber::getSubscribedEvents() (line 21 of /var/www/html/openideal-composer/web/profiles/contrib/idea/modules/openideal_idea/src/EventSubscriber/OpenidealIdeaEventSubscriber.php) #0 /var/www/html/openideal-composer/web/core/lib/Drupal/Core/DependencyInjection/Compiler/RegisterEventSubscribersPass.php(37): Drupal\openideal_idea\EventSubscriber\OpenidealIdeaEventSubscriber::getSubscribedEvents()

**Comment by zohar** [comment]
Hi @ibwo88 , can you confirm you ran the installation command as described in https://github.com/linnovate/openideal#build ?

**Comment by ibwo88** [comment]
@zohar hi, yes I tried the installation step as described. And also tried the manual module install.
I also noticed there is no Events folder under the content_moderation core. Wonder if this class has been removed?

https://git.drupalcode.org/project/drupal/-/tree/8.9.x/core/modules/content_moderation/src

**Comment by ibwo88** [comment]
Is it only me facing installation issue? What is the supported drupal version?

**Comment by zohar** [comment]
@ibwo88 Sorry I missed your earlier response. 
We did have a broken installation with the master version until a few days ago, but it has been fixed. 
Also, using the official release (3.0.3) should not yield in errors. 
make sure you run composer with `--no-cache`

We will also be releasing a new version very soon.

**Comment by elrond1337** [comment]
@zohar same issue here, also with 3.0.3 release on drupal 8.9.11 and PHP 7.4.13. Any othe hint for solving the problem?

**Comment by Artmir** [comment]
Increase php limits. Don't use web browser installation for quick and error-free installation. I already am running a copy of this on production site. Very minor issues mainly with administration i.e. still can't delete custom fields that I create. Which I think the issue may rely on the layout module. Been on holiday for a while and haven't had the time to get back to the issue.

**Comment by michpull** [comment]
@zohar same issue with 3.0.5,  Drupal 8.9.13 and PHP 7.1.26 and also tried the manual module install, no way.
With drush errors on modules ajax_comments, ckeditor_mentions, group_roles_management too :(
Any  hint?

**Comment by uncappedshady** [comment]
> @zohar same issue with 3.0.5, Drupal 8.9.13 and PHP 7.1.26 and also tried the manual module install, no way.
> With drush errors on modules ajax_comments, ckeditor_mentions, group_roles_management too :(
> Any hint?

I had the same issues with modules being missing as you have mentioned. I manually installed the modules and then I was able to proceed further but I am now stuck on the below error:

`error] Error: Class 'Drupal\content_moderation\Event\ContentModerationEvents' not found in Drupal\openideal_idea\EventSubscriber\`

**Comment by devadiga-navya** [comment]
I have been facing the similar issue .

Error: Class 'Drupal\content_moderation\Event\ContentModerationEvents' not found in C:\xampp\htdocs\openideal\web\profiles\contrib\idea\modules\openideal_idea\src\EventSubscriber\OpenidealIdeaEventSubscriber.php on line 21 #0 C:\xampp\htdocs\openideal\web\core\lib\Drupal\Core\DependencyInjection\Compiler\RegisterEventSubscribersPass.php(37): Drupal\openideal_idea\EventSubscriber\OpenidealIdeaEventSubscriber::getSubscribedEvents()
#1

I have followed the build steps given . Using 3.0.3 release on drupal 8.9.11 and PHP 7.4.13.

Any resolution steps ?

**Comment by zohar** [comment]
Can you update to the latest release and try again?
`composer create-project linnovate/openideal` should get you the latest
release.

**Comment by devadiga-navya** [comment]
Hello Zohar,

Thank you for your response. 

I was able to setup openideal successfully. The problem was that particular Drupal patch had failed during create project.

Manually applying the failed patch fixed the issue .


Regards,
Navya

**Comment by vinodsashi** [comment]
@devadiga-navya 
Can you please suggest which exact Drupal patch you installed to resolve this issue ?
Thanks in advance.
