### ISSUE TITLE
Fresh install not working

### ISSUE THREAD

**Issue by claudiopolis** [linnovate/openideal#14]
Installation instructions don't work for latest version of drush (8.1.11, installed via composer), as the [make command requires an absolute path, not a relative path](https://github.com/drush-ops/drush/issues/1856).

Once installed and all modules enabled, two instances of this error appear on all pages:
Notice: Trying to get property of non-object in block_block_view() (line 247 of /home/ctoil/public_html/modules/block/block.module).
(enabled modules listed below - I had to guess what was necessary, since there appears to be no documentation or forums)

When trying to then update modules using drush, I get the following error:
Error while trying to find the common path for enabled extensions of project idea. Extensions are:           [error]
add_idea_autocomplete, fb_post_rules, fe_challenge, fe_default, fe_development_tools, fe_dummy_content,
fe_head_banner, fe_idea, fe_member, fe_merge, fe_news, fe_notifications, fe_pages, fe_permissions,
fe_sidebar_first, fe_user, fe_user_activity, ideal_analytics, ideal_blocks, ideal_challenge, ideal_comments,
ideal_idea, ideal_main, ideal_panels_layouts, ideal_panes, ideal_suggestions,
panels_bootstrap_layout_builder.

**Comment by claudiopolis** [comment]
Sorry, left out the modules list:

drush pm-list --status="enabled"
 Package                              Name                                             Type    Version        
 Administration                       User Settings Access (user_settings_access)      Module  7.x-1.0        
 Background Images                    Background Image (bg_image)                      Module  7.x-1.4        
 Chaos tool suite                     Chaos tools (ctools)                             Module  7.x-1.10       
 Chaos tool suite                     Page manager (page_manager)                      Module  7.x-1.10       
 Chaos tool suite                     Views content panes (views_content)              Module  7.x-1.10       
 Charting                             Google Chart Tools (google_chart_tools)          Module  7.x-1.4        
 Charting                             Site analytics dashboard (analytics_dashboard)   Module  7.x-1.4        
 Context                              Context (context)                                Module  7.x-3.6        
 Core                                 Block (block)                                    Module  7.54           
 Core                                 Color (color)                                    Module  7.54           
 Core                                 Comment (comment)                                Module  7.54           
 Core                                 Contextual links (contextual)                    Module  7.54           
 Core                                 Dashboard (dashboard)                            Module  7.54           
 Core                                 Database logging (dblog)                         Module  7.54           
 Core                                 Field (field)                                    Module  7.54           
 Core                                 Field SQL storage (field_sql_storage)            Module  7.54           
 Core                                 Field UI (field_ui)                              Module  7.54           
 Core                                 File (file)                                      Module  7.54           
 Core                                 Filter (filter)                                  Module  7.54           
 Core                                 Help (help)                                      Module  7.54           
 Core                                 Image (image)                                    Module  7.54           
 Core                                 List (list)                                      Module  7.54           
 Core                                 Locale (locale)                                  Module  7.54           
 Core                                 Menu (menu)                                      Module  7.54           
 Core                                 Node (node)                                      Module  7.54           
 Core                                 Number (number)                                  Module  7.54           
 Core                                 Options (options)                                Module  7.54           
 Core                                 Overlay (overlay)                                Module  7.54           
 Core                                 Path (path)                                      Module  7.54           
 Core                                 PHP filter (php)                                 Module  7.54           
 Core                                 RDF (rdf)                                        Module  7.54           
 Core                                 Search (search)                                  Module  7.54           
 Core                                 Shortcut (shortcut)                              Module  7.54           
 Core                                 Statistics (statistics)                          Module  7.54           
 Core                                 System (system)                                  Module  7.54           
 Core                                 Taxonomy (taxonomy)                              Module  7.54           
 Core                                 Text (text)                                      Module  7.54           
 Core                                 Toolbar (toolbar)                                Module  7.54           
 Core                                 Update manager (update)                          Module  7.54           
 Core                                 User (user)                                      Module  7.54           
 Date/Time                            Date (date)                                      Module  7.x-2.8        
 Date/Time                            Date API (date_api)                              Module  7.x-2.8        
 Features                             Default Content (defaultcontent)                 Module  7.x-1.0-alpha9 
 Features                             Features (features)                              Module  7.x-2.10       
 Fields                               Address Field (addressfield)                     Module  7.x-1.0        
 Fields                               Entity Reference (entityreference)               Module  7.x-1.1        
 Fields                               Entity reference prepopulate                     Module  7.x-1.5        
                                      (entityreference_prepopulate)                                           
 Fields                               Field Permissions (field_permissions)            Module  7.x-1.0-beta2  
 Fields                               Image Link Formatter (image_link_formatter)      Module  7.x-1.1        
 Fields                               Link (link)                                      Module  7.x-1.4        
 Fields                               Vote Up/Down field (vud_field)                   Module  7.x-1.0-alpha1 
 Filters                              Mentions (mentions)                              Module  7.x-1.0-beta2  
 Flags                                Flag (flag)                                      Module  7.x-2.2        
 HybridAuth                           HybridAuth (hybridauth)                          Module  7.x-2.15       
 Message                              Message (message)                                Module  7.x-1.12       
 Multilingual - Internationalization  Internationalization (i18n)                      Module  7.x-1.13       
 Multilingual - Internationalization  Rules translation (rules_i18n)                   Module  7.x-2.8        
 Multilingual - Internationalization  String translation (i18n_string)                 Module  7.x-1.13       
 Nodequeue                            Nodequeue (nodequeue)                            Module  7.x-2.0-beta1  
 OpenideaL                            fe_challenge (fe_challenge)                      Module  7.x-1.0-beta1  
 OpenideaL                            fe_default (fe_default)                          Module  7.x-3.x-dev    
 OpenideaL                            fe_head_banner (fe_head_banner)                  Module  7.x-3.x-dev    
 OpenideaL                            fe_idea (fe_idea)                                Module  7.x-1.0-beta1  
 OpenideaL                            fe_member (fe_member)                            Module  7.x-3.x-dev    
 OpenideaL                            fe_merge (fe_merge)                              Module  7.x-3.x-dev    
 OpenideaL                            fe_news (fe_news)                                Module  7.x-3.x-dev    
 OpenideaL                            fe_pages (fe_pages)                              Module  7.x-1.0-beta1  
 OpenideaL                            fe_permissions (fe_permissions)                  Module  7.x-3.x-dev    
 OpenideaL                            fe_sidebar first (fe_sidebar_first)              Module  7.x-3.x-dev    
 OpenideaL                            fe_user (fe_user)                                Module  7.x-1.0-beta1  
 OpenideaL                            fe_user_activity (fe_user_activity)              Module  7.x-3.x-dev    
 openideaL                            Ideal analytics (ideal_analytics)                Module  7.x-2.7+0-dev  
 openideaL                            Ideal Blocks (ideal_blocks)                      Module  7.x-2.7+0-dev  
 openideaL                            Ideal Challenge (ideal_challenge)                Module  7.x-2.7+0-dev  
 openideaL                            Ideal Main (ideal_main)                          Module  7.x-2.7+0-dev  
 openideaL                            Ideal Panes (ideal_panes)                        Module  7.x-2.7+0-dev  
 OpenideaL                            OpenideaL Leader Board (openideal_leader_board)  Module                 
 Other                                Background Image UI (bg_image_ui)                Module  7.x-1.4        
 Other                                Entity API (entity)                              Module  7.x-1.6        
 Other                                Entity tokens (entity_token)                     Module  7.x-1.6        
 Other                                Hashtags (hashtags)                              Module  7.x-1.4        
 Other                                Quicktabs (quicktabs)                            Module  7.x-3.6        
 Other                                Social Buttons (social_buttons)                  Module  7.x-1.5        
 Other                                Strongarm (strongarm)                            Module  7.x-2.0        
 Other                                Token (token)                                    Module  7.x-1.6        
 Other                                Top Searches (top_searches)                      Module  7.x-1.0        
 Other                                Watcher (watcher)                                Module  7.x-1.0        
 Panels                               Mini panels (panels_mini)                        Module  7.x-3.5        
 Panels                               Panels (panels)                                  Module  7.x-3.5        
 Radioactivity                        Radioactivity (radioactivity)                    Module  7.x-2.10       
 Rules                                Rules (rules)                                    Module  7.x-2.8        
 Rules                                Voting Rules (voting_rules)                      Module  7.x-1.0-alpha1 
 Search                               Search Autocomplete (search_autocomplete)        Module  7.x-4.4        
 Theme Tools                          Block Machine Name (block_machine_name)          Module  7.x-1.0-beta1  
 Userpoints                           Userpoints (userpoints)                          Module  7.x-1.0        
 Userpoints                           Userpoints rules integration (userpoints_rules)  Module  7.x-1.0        
 Variable                             Variable (variable)                              Module  7.x-2.5        
 Views                                Views (views)                                    Module  7.x-3.14       
 Views                                Views Bootstrap (views_bootstrap)                Module  7.x-3.1        
 Views                                Views Bulk Operations (views_bulk_operations)    Module  7.x-3.3        
 Voting                               Vote Up/Down (vud)                               Module  7.x-1.0-alpha1 
 Voting                               Voting API (votingapi)                           Module  7.x-2.12       
 Core                                 Bartik (bartik)                                  Theme   7.54           
 Core                                 Seven (seven)                                    Theme   7.54

**Comment by zohar** [comment]
@claudiopolis I just tried with the latest versions of both github and drupal.org and both work without any errors.
Try the latest make file at: http://cgit.drupalcode.org/idea/tree/build-openideal.make
