### ISSUE TITLE
update process to 3.0.5 fails at updating voting api

### ISSUE THREAD

**Issue by Artmir** [linnovate/openideal#141]
A quick look at it seems it might be related to library requirement. 
![Capture11](https://user-images.githubusercontent.com/13940618/104038675-14e3e000-51de-11eb-9784-b80ae8903c77.JPG)

**Comment by Artmir** [comment]
Seems the issue is only with the tar.gz distribution. The .zip one installed without error. Worth to note that this is a localhost installation and I can see also a lot of warning messages in logs of pages not found, even though the site appears to function normally.

**Comment by Artmir** [comment]
Managed to update!
I notice now the new login module is showing the login navigation menu (login, create account, forgot password) along side with the new login interface. 
![test](https://user-images.githubusercontent.com/13940618/105705110-63041d80-5f18-11eb-8fef-a5ad9f808cb8.JPG)

**Comment by zohar** [comment]
Lol. I wonder how did that slip through the qa.
Thanks @Artmir 

@nvelychenko cc

**Comment by Artmir** [comment]
Forgot to mention this happens only if I update from 3.0.4 >3.0.5.
On a fresh install it doesn't show. I checked all settings but I can't find any difference between the two. Could it be maybe I am performing the update in wrong way? :)
![test2](https://user-images.githubusercontent.com/13940618/105708073-90eb6100-5f1c-11eb-80a1-a98d505d6835.JPG)

**Comment by nvelychenko** [comment]
@Artmir Can you describe how you updated the distribution?

**Comment by Artmir** [comment]
I basically downloaded the 3.0.5 zip. Replaced the idea files with the
newly downloaded ones. Then ran composer update, then Drush updatedb, then
drush cc.

**Comment by nvelychenko** [comment]
@Artmir I checked the installation and found that we forgot to update some configurations. We will fix it in our next release. 
Thank you for finding this issue.

**Comment by Artmir** [comment]
@nvelychenko Thanks for checking this out. I can confirm that also in the 3.0.6 still the navigation links persist. I will see maybe I can manually remove them.
@zohar There are some major version releases for some modules i.e. the Message, Route condition etc. Is it safe to update them?

**Comment by zohar** [comment]
Our releases are tested with specific versions. I'll be happy if you can
test and confirm the new releases.
We currently don't have such an upgrade in our planning, but I'm open for
PRs..
(fyi: Our current focus is the Experts Review, and preparing a SaaS
solution for the software)

**Comment by Artmir** [comment]
@zohar thanks for the reply. I am testing it in local environment. So far I don't see any issues, but then again I need to do some more thorough testing. The main issue I guess is if you have done some custom work to these modules they may not work, or if the data is now handled differently than in the previous. The most scary one is the route condition and message. Idk how they are referenced in other modules. In any case I will fully test in the coming days on a fresh install.

**Comment by Artmir** [comment]
I can confirm the navigation menu links issue has been fixed with the 3.0.8. Updating process went smooth also.

**Comment by Artmir** [comment]
Closing the issue. It has been resolved.
