### ISSUE TITLE
Installation succeeds but no content appears: am I missing something?

### ISSUE THREAD

**Issue by micheledicosmo** [linnovate/openideal#142]
I've followed the build & installation instructions. The build succeded happily, with the installation giving warnings, 1 error, but then succeeding.

Are there additional steps required to access / add OpenIdeal in the Drupal deployment?
From the admin interface, everything looks the same (no openideal installed in the extensions section, no non-default content can be added), and the homepage (`/`) is empty as well.

```
<redacted>@drupal-vm:~/openideal-composer/web$ ../vendor/bin/drush si -y --account-name <redacted> --account-pass <redacted> --account-mail <redacted> --site-name "OpenideaL" --db-url=mys
ql://root:<redacted>@127.0.0.1/openideal idea
 You are about to:
 * DROP all tables in your 'openideal' database.
 // Do you want to continue?: yes.                                                                                      
 [notice] Starting Drupal installation. This takes a while.
 [notice] Performed install task: install_select_language
 [notice] Performed install task: install_select_profile
 [notice] Performed install task: install_load_profile
 [notice] Performed install task: install_verify_requirements
 [notice] Performed install task: install_write_profile
 [notice] Performed install task: install_verify_database_ready
 [notice] Performed install task: install_base_system
 [notice] Performed install task: install_bootstrap_full
 [notice] Performed install task: install_profile_modules
 [notice] Performed install task: install_profile_themes
 [warning] The "extra_field_block:node:idea:content_moderation_control" was not found
 [warning] The "extra_field_block:node:idea:content_moderation_control" was not found
 [warning] The "extra_field_block:node:idea:content_moderation_control" was not found
 [warning] The "extra_field_block:node:idea:content_moderation_control" was not found
 [notice] Performed install task: install_install_profile
 [notice] Performed install task: install_configure_form
sh: 1: /usr/sbin/sendmail: not found
 [error]  Error sending email (from admin@example.com to <redacted> with reply-to not set). 
 [notice] Cron run completed.
 [notice] Performed install task: install_finished
 [success] Installation complete.
```

**Comment by Artmir** [comment]
The site succeeded installing. Now you can start adding content and modifying it to your liking. When you install it, it comes empty without content.

**Comment by micheledicosmo** [comment]
@Artmir Thanks for repling. I'm lost at adding ideas. This is what I see in my homepage. What should I add in order to give the website the look I see on the OpenIdeal site?

![image](https://user-images.githubusercontent.com/701157/104378970-af1a8f80-5520-11eb-9f47-7972d0906e9c.png)

**Comment by zohar** [comment]
@micheledicosmo this looks like the installation was not completed properly.
Have you successfully ran `composer install` before that?

**Comment by micheledicosmo** [comment]
@zohar Yes, and it succeded, then ran drush from the `web` folder.
If you think the problem is in the composer, should I run composer again, maybe looking for some verbose mode?

**Comment by micheledicosmo** [comment]
I have to note: I am running this on a GCP instance, on a marketplace image of Drupal 9 (Bitnami). I wonder if Drupal there is maybe not at the default location, and therefore it gets installed in the wrong place, or some other configuration thing is not as expected by drush? (Sorry, I have zero knowledge of Drupal)

**Comment by zohar** [comment]
I haven't tested running the installation with a pre existing Drupal. I always use the composer command that brings Drupal.with.it.

You should note that despite the readiness of OI to Drupal 9, it was developed under Drupal 8.

**Comment by Muskansri1** [comment]
I am facing the same issue. Could you please let me know how you resolved it
