### ISSUE TITLE
Docker container ?

### ISSUE THREAD

**Issue by mightypanda** [linnovate/openideal#143]
Hello,
I would like to try the suite but 2GB/4GB cloud compute instances do not have enough memory to go through the composer install, they all fail with the "Killed" error during composer.

Is there a docker version already installed to try out ?

Thank you!

**Comment by zohar** [comment]
@db-Matroskeen @nvelychenko what do you think?

**Comment by nvelychenko** [comment]
@mightypanda we have an [repository](https://github.com/linnovate/openideal-on-platformsh/) for platform.sh with composer.lock file. You can try it out. 
You can also install distro on your local machine, and then deploy composer.lock file to the cloud.

Note.
Please read [this](https://stackoverflow.com/questions/42065931/why-should-i-never-run-composer-update-in-production#:~:text=composer%20install%20will%20install%20whenever,what%20is%20required%20in%20composer.) manual.

**Comment by zohar** [comment]
@mightypanda also take a look at this: https://stackoverflow.com/a/64226873/2323713

**Comment by mightypanda** [comment]
Hello Zohar,
I tried the Platform.sh template (we would like to try the application with minimal install efforts for the time being), but after drupal installation i just get: "The website encountered an unexpected error. Please try again later."

What is the low-friction method to log in and try the application?

Thank you

**Comment by zohar** [comment]
@mightypanda I heard of an issue with Platform.sh but when I tested it I didn't encounter any issue. Everything went perfectly well. 
The most frictionless installation is the one described on the readme file: install with `composer create-project` and run `drush si`

**Comment by heyyo-droid** [comment]
You can use the last version **3.0.9.1** which uses **composer 2**, which is really more memory efficient.
Just run again:
`composer create-project linnovate/openideal-composer openideal`
