### ISSUE TITLE
Composer - Memory limit command in readme file doesn't work

### ISSUE THREAD

**Issue by alagumuthiah** [linnovate/openideal#147]
When i tried to run the build commands, the composer memory error occurs. I used the command given in readme file. But it does work.
Please find the snapshot of the error.
![image](https://user-images.githubusercontent.com/57620699/109157212-bd063600-7797-11eb-8f80-bbd68ebc994b.png)

**Comment by zohar** [comment]
I see you are running on Windows. The instructions are for Mac or Linux.
I will happily add instructions for Windows if someone can provide them.

**Comment by alagumuthiah** [comment]
Can you please help me with the command for Windows?

**Comment by Artmir** [comment]
What are you using in your windows? What server, php, etc?

**Comment by Muskansri1** [comment]
We are using the below versions as of now:
                PHP version 5.6
                Composer version 1
                Xampp for php5.6

The issue that we are facing is that the php requirement for OpenIdeal and the drush version are not the same, hence we are not able to install the project.

**Comment by zohar** [comment]
@Muskansri1 indeed, Drupal now requires a higher version of PHP. I recommend that you update. 
Alternatively you can use an older version of OpenideaL from it's 7.x branches. Note that these are not supported anymore.

**Comment by Muskansri1** [comment]
Thank you @zohar, we tried with the updated version but in the end, our bootstrap fails..
Is there anything we can do about this

<img width="887" alt="Capture" src="https://user-images.githubusercontent.com/47050534/111506150-5ad59b00-876f-11eb-8943-cfd6f402cda1.PNG">

**Comment by zohar** [comment]
@Muskansri1 I'm sure there is :-D
However it's hard to do it based on the error shown here. 
I strongly suggest trying out OpenideaL using [Lando](https://lando.dev). It makes spinning new test environment a breeze.

**Comment by Muskansri1** [comment]
Thank you for the suggestion @zohar! 
Being new to this tool, could you please help me in understanding if this tool will act as a base for me to install openIdeaL and use it ?

**Comment by zohar** [comment]
Yes this is what it does. It's a local docker based environment manager.

**Comment by heyyo-droid** [comment]
Pleas try the last version **3.0.9.1** which uses **composer 2**, which is really more memory efficient
Just run:
`composer create-project linnovate/openideal-composer openideal`
