### ISSUE TITLE
After adding a member in the group 'idea', clicking the navigation tab 'view' shows empty page

### ISSUE THREAD

**Issue by Artmir** [linnovate/openideal#148]
![users are added correctly](https://user-images.githubusercontent.com/13940618/109979677-d19e7d00-7d07-11eb-86f4-2b3497c1ffc5.JPG)

![view tab shows empty](https://user-images.githubusercontent.com/13940618/109979693-d5320400-7d07-11eb-9ac8-351679c53b91.JPG)

First I thought it is a permission issue. I went and gave permissions to all but still the issue persists.

Similarly users with insufficient permissions. If they click 'edit' member, 'view member' or 'delete' member, are greeted with WSOD 'page encountered an unexpected error' message.

**Comment by zohar** [comment]
@db-Matroskeen please check this out

**Comment by Artmir** [comment]
This has been resolved in the 3.0.8. Closing.
