### ISSUE TITLE
Running 'drush cim' command ends with many errors 

### ISSUE THREAD

**Issue by Artmir** [linnovate/openideal#169]
After updating from 3.0.7 -> 3.0.8 using 'composer update', 'drush updatedb' and 'drush cr'. Then following with the final 'drush cim' git throws the following errors and changes are not applied.

![drush cim1](https://user-images.githubusercontent.com/13940618/113644468-7d334800-968d-11eb-9626-22b300f50f52.JPG)
![drush cim 2](https://user-images.githubusercontent.com/13940618/113644472-802e3880-968d-11eb-9590-c581585040be.JPG)

**Comment by heyyo-droid** [comment]
This is not the correct process to update the distribution. You can't use composer update.  

**Update to new version of OpenideaL**
At any point you can run

composer require linnovate/openideal:[version-number] where [version number] is the desired tag.
drush updb
drush cim
drush cr
