### ISSUE TITLE
Root directory size reduction

### ISSUE THREAD

**Issue by Artmir** [linnovate/openideal#175]
Not an issue but I feel that the size of the Openideal installation directory has grown exponentially. Filezilla lists around 37k files. It is twice the size of the Drupal 7 version. Am I doing something wrong or is this the way it should be?

**Comment by zohar** [comment]
@Artmir this is probably "thanks" to the composer which creates thousands of files under the `vendor` directory.

**Comment by heyyo-droid** [comment]
OpenideaL is only 5 files :-) https://github.com/linnovate/openideal-composer

But of course as soon as you execute the command `composer create-project linnovate/openideal-composer YOUR_PROJECT_NAME` composer will download Drupal itself, OpenideaL profile with all custom modules and custom theme and all contrib modules, JS libraries, and PHP dependencies in vendor folder.

Closing this issue for now. Feel free to reopen it if you have more question
