### ISSUE TITLE
Updating from 3.0.7 ->3.0.8 the user mentions do not work.

### ISSUE THREAD

**Issue by Artmir** [linnovate/openideal#181]
I updated the package from 3.0.7 -> 3.0.8 and after that I noticed that the message template for user mention does not exist, also the user notify and create message rule does not exist. The 5 star widget in statistics does not show.

Could this be related to the prompt that happens during the update? When updating via composer, a message is displayed which says rules have uncommitted changes...discard changes yes/no? If I press yes, installation continues but with the above issue. 
![answering 'yes' to discard changes prompt](https://user-images.githubusercontent.com/13940618/119244655-5e284100-bb7b-11eb-8f03-e42f503f5da6.JPG)

If I answer 'no' the update process is interrupted with error.
![answer 'no' to dicard changes prompt](https://user-images.githubusercontent.com/13940618/119244663-65e7e580-bb7b-11eb-9d6f-f95d5d6b88ca.JPG)

After saying 'yes' and after update is complete. I ran 'drush updb' and I noticed that some things are not being updated?

![Capture](https://user-images.githubusercontent.com/13940618/119244592-cf1b2900-bb7a-11eb-9369-9c9a10258c10.JPG)
![xx](https://user-images.githubusercontent.com/13940618/119244593-d04c5600-bb7a-11eb-96ed-8b3b02bccaa9.JPG)

**Comment by heyyo-droid** [comment]
Hi,
Do you have the same issue with latest version of OpenideaL

**Comment by heyyo-droid** [comment]
Please feel free to reopen if still an issue
