### ISSUE TITLE
Custom Login 

### ISSUE THREAD

**Issue by Muskansri1** [linnovate/openideal#185]
Hello,
Is it possible for us to change the current log in page and include a custom login page according to our requirement?
Also, could you please suggest from where we can make changes in the code once the project is working in our systems?

Thanks a lot!

**Comment by fogsag** [comment]
Hi,
I am not the maintainer but in drupal you can customize everything via modules or customize the login-form via child-theme and libraries.
https://www.drupal.org/docs/theming-drupal/adding-stylesheets-css-and-javascript-js-to-a-drupal-theme

**Comment by heyyo-droid** [comment]
This issue is out of scope of OpenideaL more related to Drupal.
