### ISSUE TITLE
Fresh install not working

### ISSUE THREAD

**Issue by pedrogomes-td** [linnovate/openideal#187]
Trying to setup a fresh install I am executing the following command:

```
  ../vendor/bin/drush si -y --account-name ** --account-pass ** --account-mail ** --site-name "NAME" --db-url=mysql://**:**@mysql/** idea
```
 
My database server is MySQL 8.0.26 MySQL Community Server

```
In SqlContentEntityStorage.php line 1619:

  Exception thrown while performing a schema update. SQLSTATE[42000]: Syntax   
  error or access violation: 1064 You have an error in your SQL syntax; check  
   the manual that corresponds to your MySQL server version for the right syn  
  tax to use near 'groups (                                                    
  `id` INT unsigned NOT NULL auto_increment,                                   
  `type` VARCHAR(32) CHARACTE' at line 1: CREATE TABLE {groups} (              
  `id` INT unsigned NOT NULL auto_increment,                                   
  `type` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL CO  
  MMENT 'The ID of the target entity.',                                        
  `uuid` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,   
  `langcode` VARCHAR(12) CHARACTER SET ascii COLLATE ascii_general_ci NOT NUL  
  L,                                                                           
  PRIMARY KEY (`id`),                                                          
  UNIQUE KEY `group_field__uuid__value` (`uuid`),                              
  INDEX `group_field__type__target_id` (`type`)                                
  ) ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4 COMMENT 'The base table for  
   group entities.'; Array                                                     
  (                                                                            
  )                                                                            
                                                                               

In Connection.php line 701:
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MySQL server v  
  ersion for the right syntax to use near 'groups (                            
  `id` INT unsigned NOT NULL auto_increment,                                   
  `type` VARCHAR(32) CHARACTE' at line 1: CREATE TABLE {groups} (              
  `id` INT unsigned NOT NULL auto_increment,                                   
  `type` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL CO  
  MMENT 'The ID of the target entity.',                                        
  `uuid` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,   
  `langcode` VARCHAR(12) CHARACTER SET ascii COLLATE ascii_general_ci NOT NUL  
  L,                                                                           
  PRIMARY KEY (`id`),                                                          
  UNIQUE KEY `group_field__uuid__value` (`uuid`),                              
  INDEX `group_field__type__target_id` (`type`)                                
  ) ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4 COMMENT 'The base table for  
   group entities.'; Array                                                     
  (                                                                            
  )                                                                            
                                                                               

In Statement.php line 59:
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MySQL server v  
  ersion for the right syntax to use near 'groups (                            
  `id` INT unsigned NOT NULL auto_increment,                                   
  `type` VARCHAR(32) CHARACTE' at line 1    
```

**Comment by armandovitale** [comment]
![sm](https://user-images.githubusercontent.com/59963954/144493226-6e5de7b8-8c44-412f-8318-8ea34829fa5f.PNG)

same problem :-( withe same configuration

**Comment by armandovitale** [comment]
> Trying to setup a fresh install I am executing the following command:
> 
> ```
>   ../vendor/bin/drush si -y --account-name ** --account-pass ** --account-mail ** --site-name "NAME" --db-url=mysql://**:**@mysql/** idea
> ```
> 
> My database server is MySQL 8.0.26 MySQL Community Server
> 
> ```
> In SqlContentEntityStorage.php line 1619:
> 
>   Exception thrown while performing a schema update. SQLSTATE[42000]: Syntax   
>   error or access violation: 1064 You have an error in your SQL syntax; check  
>    the manual that corresponds to your MySQL server version for the right syn  
>   tax to use near 'groups (                                                    
>   `id` INT unsigned NOT NULL auto_increment,                                   
>   `type` VARCHAR(32) CHARACTE' at line 1: CREATE TABLE {groups} (              
>   `id` INT unsigned NOT NULL auto_increment,                                   
>   `type` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL CO  
>   MMENT 'The ID of the target entity.',                                        
>   `uuid` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,   
>   `langcode` VARCHAR(12) CHARACTER SET ascii COLLATE ascii_general_ci NOT NUL  
>   L,                                                                           
>   PRIMARY KEY (`id`),                                                          
>   UNIQUE KEY `group_field__uuid__value` (`uuid`),                              
>   INDEX `group_field__type__target_id` (`type`)                                
>   ) ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4 COMMENT 'The base table for  
>    group entities.'; Array                                                     
>   (                                                                            
>   )                                                                            
>                                                                                
> 
> In Connection.php line 701:
>                                                                                
>   SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
>   n your SQL syntax; check the manual that corresponds to your MySQL server v  
>   ersion for the right syntax to use near 'groups (                            
>   `id` INT unsigned NOT NULL auto_increment,                                   
>   `type` VARCHAR(32) CHARACTE' at line 1: CREATE TABLE {groups} (              
>   `id` INT unsigned NOT NULL auto_increment,                                   
>   `type` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL CO  
>   MMENT 'The ID of the target entity.',                                        
>   `uuid` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,   
>   `langcode` VARCHAR(12) CHARACTER SET ascii COLLATE ascii_general_ci NOT NUL  
>   L,                                                                           
>   PRIMARY KEY (`id`),                                                          
>   UNIQUE KEY `group_field__uuid__value` (`uuid`),                              
>   INDEX `group_field__type__target_id` (`type`)                                
>   ) ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4 COMMENT 'The base table for  
>    group entities.'; Array                                                     
>   (                                                                            
>   )                                                                            
>                                                                                
> 
> In Statement.php line 59:
>                                                                                
>   SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
>   n your SQL syntax; check the manual that corresponds to your MySQL server v  
>   ersion for the right syntax to use near 'groups (                            
>   `id` INT unsigned NOT NULL auto_increment,                                   
>   `type` VARCHAR(32) CHARACTE' at line 1    
> ```



> Trying to setup a fresh install I am executing the following command:
> 
> ```
>   ../vendor/bin/drush si -y --account-name ** --account-pass ** --account-mail ** --site-name "NAME" --db-url=mysql://**:**@mysql/** idea
> ```
> 
> My database server is MySQL 8.0.26 MySQL Community Server
> 
> ```
> In SqlContentEntityStorage.php line 1619:
> 
>   Exception thrown while performing a schema update. SQLSTATE[42000]: Syntax   
>   error or access violation: 1064 You have an error in your SQL syntax; check  
>    the manual that corresponds to your MySQL server version for the right syn  
>   tax to use near 'groups (                                                    
>   `id` INT unsigned NOT NULL auto_increment,                                   
>   `type` VARCHAR(32) CHARACTE' at line 1: CREATE TABLE {groups} (              
>   `id` INT unsigned NOT NULL auto_increment,                                   
>   `type` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL CO  
>   MMENT 'The ID of the target entity.',                                        
>   `uuid` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,   
>   `langcode` VARCHAR(12) CHARACTER SET ascii COLLATE ascii_general_ci NOT NUL  
>   L,                                                                           
>   PRIMARY KEY (`id`),                                                          
>   UNIQUE KEY `group_field__uuid__value` (`uuid`),                              
>   INDEX `group_field__type__target_id` (`type`)                                
>   ) ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4 COMMENT 'The base table for  
>    group entities.'; Array                                                     
>   (                                                                            
>   )                                                                            
>                                                                                
> 
> In Connection.php line 701:
>                                                                                
>   SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
>   n your SQL syntax; check the manual that corresponds to your MySQL server v  
>   ersion for the right syntax to use near 'groups (                            
>   `id` INT unsigned NOT NULL auto_increment,                                   
>   `type` VARCHAR(32) CHARACTE' at line 1: CREATE TABLE {groups} (              
>   `id` INT unsigned NOT NULL auto_increment,                                   
>   `type` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL CO  
>   MMENT 'The ID of the target entity.',                                        
>   `uuid` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,   
>   `langcode` VARCHAR(12) CHARACTER SET ascii COLLATE ascii_general_ci NOT NUL  
>   L,                                                                           
>   PRIMARY KEY (`id`),                                                          
>   UNIQUE KEY `group_field__uuid__value` (`uuid`),                              
>   INDEX `group_field__type__target_id` (`type`)                                
>   ) ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4 COMMENT 'The base table for  
>    group entities.'; Array                                                     
>   (                                                                            
>   )                                                                            
>                                                                                
> 
> In Statement.php line 59:
>                                                                                
>   SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
>   n your SQL syntax; check the manual that corresponds to your MySQL server v  
>   ersion for the right syntax to use near 'groups (                            
>   `id` INT unsigned NOT NULL auto_increment,                                   
>   `type` VARCHAR(32) CHARACTE' at line 1    
> ```

**Hi, I solved installing MySql server 5.7.**

**Comment by heyyo-droid** [comment]
You can use the last version **3.0.9.1** which uses **composer 2**.
Just run again:
`composer create-project linnovate/openideal-composer openideal`

**Comment by vinodsashi** [comment]
I ran into the same issue while installing. As per your recommendation, I took the latest OpenIdeal version "3.0.9.1" which uses composer 2 but still have the same issue with MySQL v8.0.19.
The I took latest OpenIdeal version "3.0.9.9" and still have the same issue.

Is this latest version still not compatible with MySQL 8 ?
Could you please let us the resolution please.
