### ISSUE TITLE
Problem Installation

### ISSUE THREAD

**Issue by rfgallon** [linnovate/openideal#188]
After composer install according Build instructions, I run the command, but received an error.

`../vendor/bin/drush si -y --account-name **** --account-pass *** --account-mail **@**** --site-name "OpenideaL" --db-url=mysql://openideal:****@127.0.0.1/openideal idea`

This is the error message:

` [notice] Starting Drupal installation. This takes a while.
 [notice] Performed install task: install_select_language
 [notice] Performed install task: install_select_profile
 [notice] Performed install task: install_load_profile
 [notice] Performed install task: install_verify_requirements
 [notice] Performed install task: install_settings_form
 [notice] Performed install task: install_write_profile
 [notice] Performed install task: install_verify_database_ready
 [notice] Performed install task: install_base_system
 [notice] Performed install task: install_bootstrap_full
 [warning] The following module is missing from the file system: realname bootstrap.inc:295

In ExtensionListTrait.php line 53:

  **The module realname does not exist.`**

Someone can help me?

**Comment by fogsag** [comment]
Same Problem for me. Solution:
Before running the installation command install the module realname:
composer require drupal/realname

**Comment by rfgallon** [comment]
@fogsag thank you
