### ISSUE TITLE
openideal_theme does not exist

### ISSUE THREAD

**Issue by rfgallon** [linnovate/openideal#189]
After installation I can't access the application.
In apache log there is this message:

`[Fri Sep 10 16:43:15.574696 2021] [php7:notice] [pid 21560] [client 187.95.112.35:52952] Uncaught PHP Exception Drupal\\Core\\Extension\\Exception\\UnknownExtensionException: "The theme openideal_theme does not exist." at /var/www/html/openideal/web/core/lib/Drupal/Core/Extension/ThemeHandler.php line 208`

**Comment by DarrenWainwright** [comment]
@rfgallon - Do you mind sharing how you got passed this error? I'm experiencing the same. 

cheers.
