### ISSUE TITLE
Installation completes but no style on website and links hit 404's

### ISSUE THREAD

**Issue by DarrenWainwright** [linnovate/openideal#192]
I've followed the instructions in the readme to install. In short:

* Built an Ubuntu VM and made sure prerequisites for Drupal are installed
* Created a DB
* Navigated to /var/www and ran `composer create-project linnovate/openideal-composer openideal`
* Navigated to /var/www/openideal and ran `composer require drupal/realname` (fails if this isn't used)
* Navigated to /var/www/openidea/web and ran the drush command from the readme, with my own values
  * This seems so very brittle - many attempts end with `y` being scrolled on in my termial
  * When i do get a successful install I then open my URL and visit my base url https://my.website.com and get the screen below...

![image](https://user-images.githubusercontent.com/59536329/144280746-cd73df14-7ae1-4a5d-8072-409b9debde16.png)

When you view the console you see the errors..

![image](https://user-images.githubusercontent.com/59536329/144280869-32d47552-2d01-41e0-8673-23c04cad0786.png)

If i click any of the links in the above page I get 404's

System info:
* Ubuntu 20..
* MariaDB
* php7.2

I have tried this several times now and have no clue what step I'm missing.

How do i actually install this?

thanks

**Comment by heyyo-droid** [comment]
Pleas try the last version **3.0.9.1** which uses **composer 2**.
Recommended also to use PHP 7.4
Just run:
`composer create-project linnovate/openideal-composer openideal`

**Comment by DarrenWainwright** [comment]
> Pleas try the last version **3.0.9.1** which uses **composer 2**. Recommended also to use PHP 7.4 Just run: `composer create-project linnovate/openideal-composer openideal`

Hi there,

I've tried again and can't get this running at all, with any of the instructions.

Most recently I've tried the follpwing on a ubuntu 20.04 with PHP 7.4 and all DB server setup along with Composer 2.

1. navigated to /var/www and ran `composer create-project linnovate/openideal-composer openideal`
2. `cd openideal`
3. ran command `/vendor/bin/drush si -y --account-name admin --account-pass "X" --account-mail X --site-name “Idea Factory” --db-url=mysql://X@localhost/openideal idea`
4. get a screen full of `empty needle ExtensionDiscovery.php:283` errors


I give up

**Comment by heyyo-droid** [comment]
I didn't test it with drush installation, but regular installation via Drupal UI should work.

**Comment by heyyo-droid** [comment]
I just tried with drush installation it worked with no issue. But pay attention how you wrote **--site-name** it should be `"` instead of `“`.
```
drush si -y --site-name="Idea Factory" --db-url=sqlite://sites/default/files/.openideal.sqlite idea -v
```
