### ISSUE TITLE
drupal/core-recommended dependencies problem

### ISSUE THREAD

**Issue by armandovitale** [linnovate/openideal#193]
After given

COMPOSER_MEMORY_LIMIT=-1 composer create-project linnovate/openideal-composer openideal

is thrown this stack exception

  Problem 1
    - drupal/core-recommended 8.9.20 requires drupal/core 8.9.20 -> satisfiable by drupal/core[8.9.20].
    - Conclusion: don't install drupal/core 8.9.20
    - drupal/core-recommended 8.9.19 requires drupal/core 8.9.19 -> satisfiable by drupal/core[8.9.19].
    - Conclusion: don't install drupal/core 8.9.19
    - drupal/core-recommended 8.9.18 requires drupal/core 8.9.18 -> satisfiable by drupal/core[8.9.18].
    - Conclusion: don't install drupal/core 8.9.18
    - drupal/core-recommended 8.9.17 requires drupal/core 8.9.17 -> satisfiable by drupal/core[8.9.17].
    - Conclusion: don't install drupal/core 8.9.17
    - drupal/core-recommended 8.9.16 requires drupal/core 8.9.16 -> satisfiable by drupal/core[8.9.16].
    - Conclusion: don't install drupal/core 8.9.16
    - drupal/core-recommended 8.9.15 requires drupal/core 8.9.15 -> satisfiable by drupal/core[8.9.15].
    - Conclusion: don't install drupal/core 8.9.15
    - drupal/core-recommended 8.9.14 requires drupal/core 8.9.14 -> satisfiable by drupal/core[8.9.14].
    - Conclusion: don't install drupal/core 8.9.14
    - drupal/core-recommended 8.9.13 requires drupal/core 8.9.13 -> satisfiable by drupal/core[8.9.13].
    - Conclusion: don't install drupal/core 8.9.13
    - drupal/core-recommended 8.9.12 requires drupal/core 8.9.12 -> satisfiable by drupal/core[8.9.12].
    - Conclusion: don't install drupal/core 8.9.12
    - drupal/core-recommended 8.9.11 requires drupal/core 8.9.11 -> satisfiable by drupal/core[8.9.11].
    - Conclusion: don't install drupal/core 8.9.11
    - drupal/core-recommended 8.9.10 requires drupal/core 8.9.10 -> satisfiable by drupal/core[8.9.10].
    - Conclusion: don't install drupal/core 8.9.10
    - drupal/core-recommended 8.9.9 requires drupal/core 8.9.9 -> satisfiable by drupal/core[8.9.9].
    - Conclusion: don't install drupal/core 8.9.9
    - drupal/core-recommended 8.9.8 requires drupal/core 8.9.8 -> satisfiable by drupal/core[8.9.8].
    - Conclusion: don't install drupal/core 8.9.8
    - drupal/core-recommended 8.9.7 requires drupal/core 8.9.7 -> satisfiable by drupal/core[8.9.7].
    - Conclusion: don't install drupal/core 8.9.7
    - drupal/core-recommended 8.9.6 requires drupal/core 8.9.6 -> satisfiable by drupal/core[8.9.6].
    - Conclusion: don't install drupal/core 8.9.6
    - drupal/core-recommended 8.9.5 requires drupal/core 8.9.5 -> satisfiable by drupal/core[8.9.5].
    - Conclusion: don't install drupal/core 8.9.5
    - drupal/core-recommended 8.9.4 requires drupal/core 8.9.4 -> satisfiable by drupal/core[8.9.4].
    - Conclusion: don't install drupal/core 8.9.4
    - drupal/core-recommended 8.9.3 requires drupal/core 8.9.3 -> satisfiable by drupal/core[8.9.3].
    - Conclusion: don't install drupal/core 8.9.3
    - drupal/core-recommended 8.9.2 requires drupal/core 8.9.2 -> satisfiable by drupal/core[8.9.2].
    - Conclusion: don't install drupal/core 8.9.2
    - drupal/core-recommended 8.9.1 requires drupal/core 8.9.1 -> satisfiable by drupal/core[8.9.1].
    - Conclusion: don't install drupal/core 8.9.1
    - drupal/core-recommended 8.9.0 requires drupal/core 8.9.0 -> satisfiable by drupal/core[8.9.0].
    - Conclusion: don't install drupal/core 8.9.0
    - drupal/core-recommended 8.8.12 requires drupal/core 8.8.12 -> satisfiable by drupal/core[8.8.12].
    - Conclusion: don't install drupal/core 8.8.12
    - drupal/core-recommended 8.8.11 requires drupal/core 8.8.11 -> satisfiable by drupal/core[8.8.11].
    - Conclusion: don't install drupal/core 8.8.11
    - drupal/core-recommended 8.8.10 requires drupal/core 8.8.10 -> satisfiable by drupal/core[8.8.10].
    - Conclusion: don't install drupal/core 8.8.10
    - drupal/core-recommended 8.8.9 requires drupal/core 8.8.9 -> satisfiable by drupal/core[8.8.9].
    - Conclusion: don't install drupal/core 8.8.9
    - drupal/core-recommended 8.8.8 requires drupal/core 8.8.8 -> satisfiable by drupal/core[8.8.8].
    - Conclusion: don't install drupal/core 8.8.8
    - drupal/core-recommended 8.8.7 requires drupal/core 8.8.7 -> satisfiable by drupal/core[8.8.7].
    - Conclusion: don't install drupal/core 8.8.7
    - drupal/core-recommended 8.9.x-dev requires drupal/core 8.9.x-dev -> satisfiable by drupal/core[8.9.x-dev].
    - Conclusion: don't install drupal/core 8.9.x-dev
    - drupal/core-recommended 8.8.x-dev requires drupal/core 8.8.x-dev -> satisfiable by drupal/core[8.8.x-dev].
    - Conclusion: don't install drupal/core 8.8.x-dev
    - drupal/core-recommended 8.8.6 requires drupal/core 8.8.6 -> satisfiable by drupal/core[8.8.6].
    - Conclusion: don't install drupal/core 8.8.6
    - drupal/core-recommended 8.8.5 requires drupal/core 8.8.5 -> satisfiable by drupal/core[8.8.5].
    - Conclusion: don't install drupal/core 8.8.5
    - drupal/core-recommended 8.8.4 requires drupal/core 8.8.4 -> satisfiable by drupal/core[8.8.4].
    - Conclusion: don't install drupal/core 8.8.4
    - drupal/core-recommended 8.8.3 requires drupal/core 8.8.3 -> satisfiable by drupal/core[8.8.3].
    - Conclusion: don't install drupal/core 8.8.3
    - drupal/core-recommended 8.8.2 requires drupal/core 8.8.2 -> satisfiable by drupal/core[8.8.2].
    - Conclusion: don't install drupal/core 8.8.2
    - drupal/core-recommended 8.8.1 requires drupal/core 8.8.1 -> satisfiable by drupal/core[8.8.1].
    - Conclusion: don't install drupal/core 8.8.1
    - drupal/core-recommended 8.8.0 requires drupal/core 8.8.0 -> satisfiable by drupal/core[8.8.0].
    - Conclusion: don't install drupal/core 8.8.0
    - drupal/core-recommended 8.9.0-rc1 requires drupal/core 8.9.0-rc1 -> satisfiable by drupal/core[8.9.0-rc1].
    - Conclusion: don't install drupal/core 8.9.0-rc1
    - drupal/core-recommended 8.8.0-rc1 requires drupal/core 8.8.0-rc1 -> satisfiable by drupal/core[8.8.0-rc1].
    - Conclusion: don't install drupal/core 8.8.0-rc1
    - drupal/core-recommended 8.9.0-beta3 requires drupal/core 8.9.0-beta3 -> satisfiable by drupal/core[8.9.0-beta3].
    - Conclusion: don't install drupal/core 8.9.0-beta3
    - Installation request for drupal/rules 3.x-dev#7d1833f -> satisfiable by drupal/rules[3.x-dev].
    - drupal/core-recommended 8.9.0-beta2 requires drupal/core 8.9.0-beta2 -> satisfiable by drupal/core[8.9.0-beta2].
    - Conclusion: don't install drupal/core 8.9.0-beta2
    - drupal/core-recommended 8.9.0-beta1 requires drupal/core 8.9.0-beta1 -> satisfiable by drupal/core[8.9.0-beta1].
    - Conclusion: don't install drupal/core 8.9.0-beta1
    - drupal/rules 3.x-dev requires drupal/core ^9 -> satisfiable by drupal/core[9.0.0, 9.0.0-alpha1, 9.0.0-alpha2, 9.0.0-beta1, 9.0.0-beta2, 9.0.0-beta3, 9.0.0-rc1, 9.0.1, 9.0.10, 9.0.11, 9.0.12, 9.0.13, 9.0.14, 9.0.2, 9.0.3, 9.0.4, 9.0.5, 9.0.6, 9.0.7, 9.0.8, 9.0.9, 9.0.x-dev, 9.1.0, 9.1.0-alpha1, 9.1.0-beta1, 9.1.0-rc1, 9.1.0-rc2, 9.1.0-rc3, 9.1.1, 9.1.10, 9.1.11, 9.1.12, 9.1.13, 9.1.14, 9.1.15, 9.1.2, 9.1.3, 9.1.4, 9.1.5, 9.1.6, 9.1.7, 9.1.8, 9.1.9, 9.1.x-dev, 9.2.0, 9.2.0-alpha1, 9.2.0-beta1, 9.2.0-beta2, 9.2.0-beta3, 9.2.0-rc1, 9.2.1, 9.2.10, 9.2.2, 9.2.3, 9.2.4, 9.2.5, 9.2.6, 9.2.7, 9.2.8, 9.2.9, 9.2.x-dev, 9.3.0, 9.3.0-alpha1, 9.3.0-beta1, 9.3.0-beta2, 9.3.0-beta3, 9.3.0-rc1, 9.3.x-dev, 9.4.x-dev].
    - Can only install one of: drupal/core[9.0.0, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.0-alpha1, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.0-alpha2, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.0-beta1, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.0-beta2, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.0-beta3, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.0-rc1, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.1, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.10, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.11, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.12, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.13, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.14, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.2, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.3, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.4, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.5, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.6, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.7, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.8, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.9, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.0.x-dev, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.0, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.0-alpha1, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.0-beta1, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.0-rc1, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.0-rc2, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.0-rc3, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.1, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.10, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.11, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.12, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.13, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.14, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.15, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.2, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.3, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.4, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.5, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.6, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.7, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.8, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.9, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.1.x-dev, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.2.0, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.2.0-alpha1, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.2.0-beta1, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.2.0-beta2, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.2.0-beta3, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.2.0-rc1, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.2.1, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.2.10, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.2.2, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.2.3, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.2.4, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.2.5, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.2.6, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.2.7, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.2.8, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.2.9, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.2.x-dev, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.3.0, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.3.0-alpha1, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.3.0-beta1, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.3.0-beta2, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.3.0-beta3, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.3.0-rc1, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.3.x-dev, 8.8.0-beta1].
    - Can only install one of: drupal/core[9.4.x-dev, 8.8.0-beta1].
    - drupal/core-recommended 8.8.0-beta1 requires drupal/core 8.8.0-beta1 -> satisfiable by drupal/core[8.8.0-beta1].
    - Installation request for drupal/core-recommended ^8.8 -> satisfiable by drupal/core-recommended[8.8.0, 8.8.0-beta1, 8.8.0-rc1, 8.8.1, 8.8.10, 8.8.11, 8.8.12, 8.8.2, 8.8.3, 8.8.4, 8.8.5, 8.8.6, 8.8.7, 8.8.8, 8.8.9, 8.8.x-dev, 8.9.0, 8.9.0-beta1, 8.9.0-beta2, 8.9.0-beta3, 8.9.0-rc1, 8.9.1, 8.9.10, 8.9.11, 8.9.12, 8.9.13, 8.9.14, 8.9.15, 8.9.16, 8.9.17, 8.9.18, 8.9.19, 8.9.2, 8.9.20, 8.9.3, 8.9.4, 8.9.5, 8.9.6, 8.9.7, 8.9.8, 8.9.9, 8.9.x-dev].

**Comment by heyyo-droid** [comment]
Pleas try the last version **3.0.9.1** which uses **composer 2**.
Just run:
`composer create-project linnovate/openideal-composer openideal`

**Comment by monofox** [comment]
Tested with openideal 3.0.9.2 and composer 2.1.12 and php 7.4. 
```
Creating a "linnovate/openideal-composer" project at "./openideal"
Info from https://repo.packagist.org: #StandWithUkraine
Installing linnovate/openideal-composer (3.0.9.2)
  - Installing linnovate/openideal-composer (3.0.9.2): Extracting archive
Created project in /var/www/virtual/ideas/openideal
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Dependency resolution completed in 1.361 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires linnovate/openideal ^3.0 -> satisfiable by linnovate/openideal[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.8.1, 3.0.8.2, 3.0.9, 3.0.9.1, 3.0.9.2, 3.x-dev].
    - drupal/core-recommended 8.8.7 requires drupal/core 8.8.7 -> satisfiable by drupal/core[8.8.7].
    - Conclusion: don't install drupal/core 8.8.7 (conflict analysis result)
    - drupal/core-recommended 8.8.8 requires drupal/core 8.8.8 -> satisfiable by drupal/core[8.8.8].
    - Conclusion: don't install drupal/core 8.8.8 (conflict analysis result)
    - drupal/core-recommended 8.8.9 requires drupal/core 8.8.9 -> satisfiable by drupal/core[8.8.9].
    - Conclusion: don't install drupal/core 8.8.9 (conflict analysis result)
    - drupal/core-recommended 8.8.10 requires drupal/core 8.8.10 -> satisfiable by drupal/core[8.8.10].
    - Conclusion: don't install drupal/core 8.8.10 (conflict analysis result)
    - drupal/core-recommended 8.8.11 requires drupal/core 8.8.11 -> satisfiable by drupal/core[8.8.11].
    - Conclusion: don't install drupal/core 8.8.11 (conflict analysis result)
    - drupal/core-recommended 8.8.12 requires drupal/core 8.8.12 -> satisfiable by drupal/core[8.8.12].
    - Conclusion: don't install drupal/core 8.8.12 (conflict analysis result)
    - drupal/core-recommended 8.9.0 requires drupal/core 8.9.0 -> satisfiable by drupal/core[8.9.0].
    - Conclusion: don't install drupal/core 8.9.0 (conflict analysis result)
    - drupal/core-recommended 8.9.1 requires drupal/core 8.9.1 -> satisfiable by drupal/core[8.9.1].
    - Conclusion: don't install drupal/core 8.9.1 (conflict analysis result)
    - drupal/core-recommended 8.9.2 requires drupal/core 8.9.2 -> satisfiable by drupal/core[8.9.2].
    - Conclusion: don't install drupal/core 8.9.2 (conflict analysis result)
    - drupal/core-recommended 8.9.3 requires drupal/core 8.9.3 -> satisfiable by drupal/core[8.9.3].
    - Conclusion: don't install drupal/core 8.9.3 (conflict analysis result)
    - drupal/core-recommended 8.9.4 requires drupal/core 8.9.4 -> satisfiable by drupal/core[8.9.4].
    - Conclusion: don't install drupal/core 8.9.4 (conflict analysis result)
    - drupal/core-recommended 8.9.5 requires drupal/core 8.9.5 -> satisfiable by drupal/core[8.9.5].
    - Conclusion: don't install drupal/core 8.9.5 (conflict analysis result)
    - drupal/core-recommended 8.9.6 requires drupal/core 8.9.6 -> satisfiable by drupal/core[8.9.6].
    - Conclusion: don't install drupal/core 8.9.6 (conflict analysis result)
    - drupal/core-recommended 8.9.7 requires drupal/core 8.9.7 -> satisfiable by drupal/core[8.9.7].
    - Conclusion: don't install drupal/core 8.9.7 (conflict analysis result)
    - drupal/core-recommended 8.9.8 requires drupal/core 8.9.8 -> satisfiable by drupal/core[8.9.8].
    - Conclusion: don't install drupal/core 8.9.8 (conflict analysis result)
    - drupal/core-recommended 8.9.9 requires drupal/core 8.9.9 -> satisfiable by drupal/core[8.9.9].
    - Conclusion: don't install drupal/core 8.9.9 (conflict analysis result)
    - drupal/core-recommended 8.9.10 requires drupal/core 8.9.10 -> satisfiable by drupal/core[8.9.10].
    - Conclusion: don't install drupal/core 8.9.10 (conflict analysis result)
    - drupal/core-recommended 8.9.11 requires drupal/core 8.9.11 -> satisfiable by drupal/core[8.9.11].
    - Conclusion: don't install drupal/core 8.9.11 (conflict analysis result)
    - drupal/core-recommended 8.9.12 requires drupal/core 8.9.12 -> satisfiable by drupal/core[8.9.12].
    - Conclusion: don't install drupal/core 8.9.12 (conflict analysis result)
    - drupal/core-recommended 8.9.13 requires drupal/core 8.9.13 -> satisfiable by drupal/core[8.9.13].
    - Conclusion: don't install drupal/core 8.9.13 (conflict analysis result)
    - drupal/core-recommended 8.9.14 requires drupal/core 8.9.14 -> satisfiable by drupal/core[8.9.14].
    - Conclusion: don't install drupal/core 8.9.14 (conflict analysis result)
    - drupal/core-recommended 8.9.15 requires drupal/core 8.9.15 -> satisfiable by drupal/core[8.9.15].
    - Conclusion: don't install drupal/core 8.9.15 (conflict analysis result)
    - drupal/core-recommended 8.9.16 requires drupal/core 8.9.16 -> satisfiable by drupal/core[8.9.16].
    - Conclusion: don't install drupal/core 8.9.16 (conflict analysis result)
    - drupal/core-recommended 8.9.17 requires drupal/core 8.9.17 -> satisfiable by drupal/core[8.9.17].
    - Conclusion: don't install drupal/core 8.9.17 (conflict analysis result)
    - drupal/core-recommended 8.9.18 requires drupal/core 8.9.18 -> satisfiable by drupal/core[8.9.18].
    - Conclusion: don't install drupal/core 8.9.18 (conflict analysis result)
    - drupal/core-recommended 8.9.19 requires drupal/core 8.9.19 -> satisfiable by drupal/core[8.9.19].
    - Conclusion: don't install drupal/core 8.9.19 (conflict analysis result)
    - drupal/core-recommended 8.9.20 requires drupal/core 8.9.20 -> satisfiable by drupal/core[8.9.20].
    - Conclusion: don't install drupal/core 8.9.20 (conflict analysis result)
    - drupal/votingapi 3.x-dev is an alias of drupal/votingapi dev-3.x and thus requires it to be installed too.
    - Conclusion: install drupal/votingapi 3.x-dev (conflict analysis result)
    - drupal/core-recommended[8.8.0-beta1, 8.8.0-rc1, 8.8.0, 8.8.1, 8.8.2, 8.8.3, 8.8.4, 8.8.5, 8.8.6, 8.9.0-beta1, 8.9.0-beta2, 8.9.0-beta3, 8.9.0-rc1] require composer/installers v1.7.0 -> satisfiable by composer/installers[v1.7.0].
    - drupal/core[10.0.0-alpha2, 10.0.0-alpha3, 10.0.x-dev] require php >=8.1.0 -> your php version (7.4.28) does not satisfy that requirement.
    - drupal/core 10.0.0-alpha1 requires php >=8.0.2 -> your php version (7.4.28) does not satisfy that requirement.
    - composer/installers v1.7.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.1.0] but it does not match the constraint.
    - drupal/core-recommended 8.9.x-dev requires drupal/core 8.9.x-dev -> satisfiable by drupal/core[8.9.x-dev].
    - Conclusion: don't install drupal/core 8.9.x-dev (conflict analysis result)
    - drupal/votingapi dev-3.x requires drupal/core ^9.2 || ^10 -> satisfiable by drupal/core[9.2.0-alpha1, 9.2.0-beta1, 9.2.0-beta2, 9.2.0-beta3, 9.2.0-rc1, 9.2.0, 9.2.1, 9.2.2, 9.2.3, 9.2.4, 9.2.5, 9.2.6, 9.2.7, 9.2.8, 9.2.9, 9.2.10, 9.2.11, 9.2.12, 9.2.13, 9.2.14, 9.2.15, 9.2.16, 9.2.17, 9.2.x-dev, 9.3.0-alpha1, 9.3.0-beta1, 9.3.0-beta2, 9.3.0-beta3, 9.3.0-rc1, 9.3.0, 9.3.1, 9.3.2, 9.3.3, 9.3.4, 9.3.5, 9.3.6, 9.3.7, 9.3.8, 9.3.9, 9.3.10, 9.3.11, 9.3.x-dev, 9.4.x-dev, 10.0.0-alpha1, 10.0.0-alpha2, 10.0.0-alpha3, 10.0.x-dev].
    - You can only install one version of a package, so only one of these can be installed: drupal/core[8.4.0-rc1, 8.4.0-rc2, 8.4.0, 8.4.1, 8.4.2, 8.4.3, 8.4.4, 8.4.5, 8.4.6, 8.4.7, 8.4.8, 8.4.x-dev, 8.5.0-alpha1, 8.5.0-beta1, 8.5.0-rc1, 8.5.0, 8.5.1, 8.5.2, 8.5.3, 8.5.4, 8.5.5, 8.5.6, 8.5.7, 8.5.8, 8.5.9, 8.5.10, 8.5.11, 8.5.12, 8.5.13, 8.5.14, 8.5.15, 8.5.x-dev, 8.6.0-alpha1, 8.6.0-beta1, 8.6.0-beta2, 8.6.0-rc1, 8.6.0, 8.6.1, 8.6.2, 8.6.3, 8.6.4, 8.6.5, 8.6.6, 8.6.7, 8.6.8, 8.6.9, 8.6.10, 8.6.11, 8.6.12, 8.6.13, 8.6.14, 8.6.15, 8.6.16, 8.6.17, 8.6.18, 8.7.0-alpha1, 8.7.0-alpha2, 8.7.0-beta1, 8.7.0-beta2, 8.7.0-rc1, 8.7.0, 8.7.1, 8.7.2, 8.7.3, 8.7.4, 8.7.5, 8.7.6, 8.7.7, 8.7.8, 8.7.9, 8.7.10, 8.7.11, 8.7.12, 8.7.13, 8.7.14, 8.7.x-dev, 8.8.0-alpha1, 8.8.0-beta1, 8.8.0-rc1, 8.8.0, 8.8.1, 8.8.2, 8.8.3, 8.8.4, 8.8.5, 8.8.6, 8.8.7, 8.8.8, 8.8.9, 8.8.10, 8.8.11, 8.8.12, 8.8.x-dev, 8.9.0-beta1, 8.9.0-beta2, 8.9.0-beta3, 8.9.0-rc1, 8.9.0, 8.9.1, 8.9.2, 8.9.3, 8.9.4, 8.9.5, 8.9.6, 8.9.7, 8.9.8, 8.9.9, 8.9.10, 8.9.11, 8.9.12, 8.9.13, 8.9.14, 8.9.15, 8.9.16, 8.9.17, 8.9.18, 8.9.19, 8.9.20, 8.9.x-dev, 9.0.0-alpha1, 9.0.0-alpha2, 9.0.0-beta1, 9.0.0-beta2, 9.0.0-beta3, 9.0.0-rc1, 9.0.0, 9.0.1, 9.0.2, 9.0.3, 9.0.4, 9.0.5, 9.0.6, 9.0.7, 9.0.8, 9.0.9, 9.0.10, 9.0.11, 9.0.12, 9.0.13, 9.0.14, 9.0.x-dev, 9.1.0-alpha1, 9.1.0-beta1, 9.1.0-rc1, 9.1.0-rc2, 9.1.0-rc3, 9.1.0, 9.1.1, 9.1.2, 9.1.3, 9.1.4, 9.1.5, 9.1.6, 9.1.7, 9.1.8, 9.1.9, 9.1.10, 9.1.11, 9.1.12, 9.1.13, 9.1.14, 9.1.15, 9.1.x-dev, 9.2.0-alpha1, 9.2.0-beta1, 9.2.0-beta2, 9.2.0-beta3, 9.2.0-rc1, 9.2.0, 9.2.1, 9.2.2, 9.2.3, 9.2.4, 9.2.5, 9.2.6, 9.2.7, 9.2.8, 9.2.9, 9.2.10, 9.2.11, 9.2.12, 9.2.13, 9.2.14, 9.2.15, 9.2.16, 9.2.17, 9.2.x-dev, 9.3.0-alpha1, 9.3.0-beta1, 9.3.0-beta2, 9.3.0-beta3, 9.3.0-rc1, 9.3.0, 9.3.1, 9.3.2, 9.3.3, 9.3.4, 9.3.5, 9.3.6, 9.3.7, 9.3.8, 9.3.9, 9.3.10, 9.3.11, 9.3.x-dev, 9.4.x-dev, 10.0.0-alpha1, 10.0.0-alpha2, 10.0.0-alpha3, 10.0.x-dev].
    - drupal/core-recommended 8.8.x-dev requires drupal/core 8.8.x-dev -> satisfiable by drupal/core[8.8.x-dev].
    - Root composer.json requires drupal/core-recommended ^8.8 -> satisfiable by drupal/core-recommended[8.8.0-beta1, 8.8.0-rc1, 8.8.0, 8.8.1, 8.8.2, 8.8.3, 8.8.4, 8.8.5, 8.8.6, 8.8.7, 8.8.8, 8.8.9, 8.8.10, 8.8.11, 8.8.12, 8.8.x-dev, 8.9.0-beta1, 8.9.0-beta2, 8.9.0-beta3, 8.9.0-rc1, 8.9.0, 8.9.1, 8.9.2, 8.9.3, 8.9.4, 8.9.5, 8.9.6, 8.9.7, 8.9.8, 8.9.9, 8.9.10, 8.9.11, 8.9.12, 8.9.13, 8.9.14, 8.9.15, 8.9.16, 8.9.17, 8.9.18, 8.9.19, 8.9.20, 8.9.x-dev].
```


Based on the README, the requirements specified at https://www.drupal.org/docs/system-requirements must be taken care. Based on the composer.json created, it seems like Drupal 8.8 should be used. Beginning with Drupal 8.8.3, PHP 7.4 is supported.

Executing `composer require 'drupal/core:8.8'` will get an installable set.

Executing `composer require 'drupal/core-recommended:8.8'` will produce an invalid set:
```
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - composer/installers v1.7.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.1.0] but it does not match the constraint.
    - drupal/core-recommended 8.8.0 requires composer/installers v1.7.0 -> satisfiable by composer/installers[v1.7.0].
    - Root composer.json requires drupal/core-recommended 8.8 -> satisfiable by drupal/core-recommended[8.8.0].
```

Seems like an package issue with drupal/core-recommended:8.8 -- or is it an issue to use composer 2 and we should explicitely use composer 1?

**Comment by monofox** [comment]
Update: Tested with **composer 1.7.3** -- this does not produce any Drupal issues anymore for satisfying the requirements, but resulting in:
```
pdating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - linnovate/openideal 3.0.9.1 requires ckeditor/ajax 4.14.1 -> no matching package found.
    - linnovate/openideal 3.0.9 requires ckeditor/ajax 4.14.1 -> no matching package found.
    - linnovate/openideal 3.0.8.2 requires ckeditor/ajax 4.14.1 -> no matching package found.
    - linnovate/openideal 3.0.8.1 requires ckeditor/ajax 4.14.1 -> no matching package found.
    - linnovate/openideal 3.0.8 requires ckeditor/ajax 4.14.1 -> no matching package found.
    - linnovate/openideal 3.0.7 requires ckeditor/ajax 4.14.1 -> no matching package found.
    - linnovate/openideal 3.0.6 requires ckeditor/ajax 4.14.1 -> no matching package found.
    - linnovate/openideal 3.0.5 requires ckeditor/ajax 4.14.1 -> no matching package found.
    - linnovate/openideal 3.0.4 requires ckeditor/ajax 4.14.1 -> no matching package found.
    - linnovate/openideal 3.0.3 requires ckeditor/ajax 4.14.1 -> no matching package found.
    - linnovate/openideal 3.0.2 requires ckeditor/ajax 4.14.1 -> no matching package found.
    - linnovate/openideal 3.0.1 requires ckeditor/ajax 4.14.1 -> no matching package found.
    - linnovate/openideal 3.0.0 requires ckeditor/ajax 4.14.1 -> no matching package found.
    - linnovate/openideal 3.0.9.2 requires drupal/votingapi 3.x-dev -> satisfiable by drupal/votingapi[3.x-dev].
    - linnovate/openideal 3.x-dev requires drupal/votingapi 3.x-dev -> satisfiable by drupal/votingapi[3.x-dev].
    - Conclusion: don't install drupal/votingapi 3.x-dev
    - Installation request for linnovate/openideal ^3.0 -> satisfiable by linnovate/openideal[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.8.1, 3.0.8.2, 3.0.9, 3.0.9.1, 3.0.9.2, 3.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it
```
Enforcing version 3.0.9.2 for OpenIdeaL will produce issue with dependency `bower-asset/c3` as its package cannot be found.

**Comment by monofox** [comment]
Based on the `composer.json` of `openideal`, we require:
```json
"drupal/votingapi": "3.x-dev",
```
which requires `Drupal: ^9.2 || ^10`. Might make sense to switch to stitch to version `^3.0@beta` ?

Update: i can confirm, that this solves some things. Better would be to upgrade to Drupal 9.2 for security reason (https://www.drupal.org/psa-2021-06-29):
```
Drupal 8 will reach its end-of-life on November 2, 2021, before the release of Drupal 9.3.0, due to 
Symfony 3's end-of-life. If you are using Drupal 8, you must upgrade to Drupal 9.2 before November 
to keep your site secure. (Drupal 9.1 security coverage ends shortly after the Drupal 8 end-of-life, 
so updating to 9.2 directly is best.)
```

**Comment by heyyo-droid** [comment]
Hi @monofox ,
Thanks for reporting this issue, voting_api dev branch removed compatibility to Drupal 8.82, as proposed we are now using beta branch. 
Concerning upgrade to Drupal 9, it's planned but we don't have enough resources to do it in the current days. We have lots of custom code which should be migrated too, it's not only core + contrib modules.
Stay tuned !
