### ISSUE TITLE
Openideal Installation Issues

### ISSUE THREAD

**Issue by Muskansri1** [linnovate/openideal#194]
Do we need to install and configure drupal to install Openideal?

**Comment by zohar** [comment]
Running the composer command will install drupal together with openideal

**Comment by Muskansri1** [comment]
Thank you for the reply!
I am not able to run the composer command since I'm working in a corporate environment with minimum access to the internet.
Is there any workaround?

**Comment by dvorad** [comment]
I assume we can provide a  bundled supported version with quarterly updates
and a support plan.
We have done this with several organizations
Lior

**Comment by Muskansri1** [comment]
Thank you for the suggestion :)
I'll check on that internally.. 
We had installed the Openideal application once in our environment and it was working.. I have gotten the zip of it.. so I have the vendor and web directory
Though when I try the drush command.. it is not able to access..
Could you suggest something on this please.
Thanks in advance!

**Comment by heyyo-droid** [comment]
OpenIdeal is Drupal 8 installation with a distribution profile.
You can install it via `drush si ...` command which is the fastest way but you still can install Drupal via its UI. You need to select the `OpenideaL` profile to install the OpenideaL distribution.

I'm closing this issue for now, feel free to reopen it if needed.

![image](https://user-images.githubusercontent.com/81759607/165242852-987f815d-1258-4941-927f-917f9ef39919.png)
