### ISSUE TITLE
While installing and while setup project getting multiple problem.

### ISSUE THREAD

**Issue by goutamkumarchoudhary26** [linnovate/openideal#195]
While installing and while setup project getting multiple problem.
<img width="947" alt="image" src="https://user-images.githubusercontent.com/30371773/148769943-9c06bc39-1324-43a3-ab1e-a7485900d2de.png">
<img width="940" alt="image" src="https://user-images.githubusercontent.com/30371773/148770172-f0c2308d-3be6-401f-baea-2302b86580e4.png">

**Comment by heyyo-droid** [comment]
Pleas try the last version **3.0.9.1** which uses **composer 2**.
Just run:
`composer create-project linnovate/openideal-composer openideal`
