### ISSUE TITLE
install openideal with drupal 9 shows some errors:- 

### ISSUE THREAD

**Issue by pawan809** [linnovate/openideal#202]
Problem 1
    - Root composer.json requires linnovate/openideal 3.0.9 -> satisfiable by linnovate/openideal[3.0.9].
    - linnovate/openideal 3.0.9 requires bower-asset/c3 ^0.7.20 -> could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by heyyo-droid** [comment]
OpenideaL doesn't support yet Drupal 9.  But we will work on it as soon as we have more resources.
