### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by donchi4all** [linnovate/openideal#205]
- [ ]Got this error when trying to install using composer create-project linnovate/openideal-composer openideal
<img width="1644" alt="Screenshot 2022-04-21 at 18 26 12" src="https://user-images.githubusercontent.com/33794017/164516975-ca9d629d-6403-490b-b399-353dbe9a48d7.png">

**Comment by heyyo-droid** [comment]
Hi @donchi4all ,
Thanks for reporting. You need to use php 7.4. Php 8 or 8.1 are not supported yet. 
Regards

**Comment by donchi4all** [comment]
@heyyo-droid  MY PHP version is 7.4

**Comment by donchi4all** [comment]
Hi @heyyo-droid @zohar @eyalev @konforti 
Kindly help look at this, I have successfully installed this but having issues with sql

<img width="1166" alt="Screenshot 2022-04-25 at 10 02 29" src="https://user-images.githubusercontent.com/33794017/165056906-03d54e0c-9eb0-4528-8788-72ac18fb4c61.png">

**Comment by heyyo-droid** [comment]
Hi @donchi4all ,

Some questions.

Which exact command did you execute to get this error ?
Your database was dropped before installing drupal ?
Which database and version are you using ?  

If your familiar with docker, I recommend you to use Docker4Drupal project. 
https://github.com/wodby/docker4drupal

**Comment by donchi4all** [comment]
Hi @heyyo-droid 

Which exact command did you execute to get this error ?

../vendor/bin/drush si -y --account-name cdonchi --account-pass assword@1 --account-mail cdonchi@gmail.ng --site-name "OpenideaL" --db-url=mysql://root:password@127.0.0.1/openideal idea

Your database was dropped before installing drupal ? yes

Which database and version are you using ? MySQL 8.0.28

**Comment by heyyo-droid** [comment]
I suppose it's an issue with your environment.  
I just tested the last version of the project without any issue:

With PHP 7.4 and composer 2:
- `composer create-project linnovate/openideal-composer openideal`
- Add files from docker4drupal to openideal folder
- Remove docker-compose.override.yml
- Edit .env, here only modified variable: 

```
PROJECT_NAME=openideal
PROJECT_BASE_URL=openideal.docker.localhost
DB_NAME=openideal

MARIADB_TAG=10.7-3.19.0 // You can use any version of mariadb
PHP_TAG=7.4-dev-4.36.0
NGINX_VHOST_PRESET=drupal8
```
- Pulling/starting all containers by doing `make`
- Enter the PHP container by doing `make shell`
- `cd web`
- `drush si -y --account-name admin --account-pass 123 --account-mail my_mail@example.com --site-name "Openidea
L" --db-url=mysql://drupal:drupal@mariadb/openideal idea`
- Set correct owner to sites/default/files:
` chown -R wodby:www-data sites/default/files/` 

Done. You can access your website via http://openideal.docker.localhost:8000 !


![image](https://user-images.githubusercontent.com/81759607/165077138-1aaa2b80-e230-4277-9a30-8035933ef6fa.png)

**Comment by donchi4all** [comment]
Hi @heyyo-droid ,
I followed the process you stated and ended up having this error 
<img width="1406" alt="Screenshot 2022-04-25 at 15 00 37" src="https://user-images.githubusercontent.com/33794017/165109744-ed9d4e66-6e0b-4fc6-90cd-5a9862d2d5a2.png">

**Comment by heyyo-droid** [comment]
Can you show me your .env file ?

**Comment by donchi4all** [comment]
Hi @heyyo-droid  below is the .env file
```
PROJECT_NAME=donchi_openideal_project
PROJECT_BASE_URL=openideal.docker.localhost
PROJECT_PORT=8000

DB_NAME=openideal
DB_USER=root
DB_PASSWORD=password
DB_ROOT_PASSWORD=password
DB_HOST=mariadb
DB_PORT=3306
DB_DRIVER=mysql

### --- MARIADB ----

# MARIADB_TAG=10.7-3.19.0
MARIADB_TAG=10.6-3.19.0
#MARIADB_TAG=10.5-3.19.0
#MARIADB_TAG=10.4-3.19.0
#MARIADB_TAG=10.3-3.19.0
#MARIADB_TAG=10.2-3.19.0

### --- VANILLA DRUPAL ----

DRUPAL_TAG=9-4.43.1
#DRUPAL_TAG=7-4.43.1

### --- PHP ----

# Linux (uid 1000 gid 1000)

# PHP_TAG=8.1-dev-4.36.0
#PHP_TAG=8.0-dev-4.36.0
PHP_TAG=7.4-dev-4.36.0

# macOS (uid 501 gid 20)

#PHP_TAG=8.1-dev-macos-4.36.0
#PHP_TAG=8.0-dev-macos-4.36.0
#PHP_TAG=7.4-dev-macos-4.36.0

### --- NGINX ----

NGINX_TAG=1.21-5.23.0
#NGINX_TAG=1.20-5.23.0
#NGINX_TAG=1.19-5.23.0

# NGINX_VHOST_PRESET=drupal9
NGINX_VHOST_PRESET=drupal8
#NGINX_VHOST_PRESET=drupal7

### --- SOLR ---

SOLR_TAG=8-4.17.0
#SOLR_TAG=7-4.17.0
#SOLR_TAG=6-4.17.0
#SOLR_TAG=5-4.17.0

SOLR_CONFIG_SET="search_api_solr_4.1.6"
#SOLR_CONFIG_SET="search_api_solr_4.0.1"
#SOLR_CONFIG_SET="search_api_solr_8.x-3.9"
#SOLR_CONFIG_SET="search_api_solr_8.x-3.2"
#SOLR_CONFIG_SET="search_api_solr_8.x-2.7"
#SOLR_CONFIG_SET="search_api_solr_8.x-1.2"
#SOLR_CONFIG_SET="search_api_solr_7.x-1.14"

### --- ELASTICSEARCH ---

ELASTICSEARCH_TAG=7-5.18.1
#ELASTICSEARCH_TAG=6-5.18.1

### --- KIBANA ---

KIBANA_TAG=7-5.18.1
#KIBANA_TAG=6-5.18.1

### --- REDIS ---

REDIS_TAG=6-3.12.0
#REDIS_TAG=5-3.12.0

### --- NODE ---

NODE_TAG=16-dev-1.0.0
#NODE_TAG=14-dev-1.0.0
#NODE_TAG=12-dev-1.0.0

### --- VARNISH ---

VARNISH_TAG=6.0-4.10.0
#VARNISH_TAG=4.1-4.10.0

### --- POSTGRESQL ----

POSTGRES_TAG=14-1.27.0
#POSTGRES_TAG=13-1.27.0
#POSTGRES_TAG=12-1.27.0
#POSTGRES_TAG=11-1.27.0
#POSTGRES_TAG=10-1.27.0

### OTHERS

ADMINER_TAG=4-3.22.0
APACHE_TAG=2.4-4.9.0
ATHENAPDF_TAG=2.16.0
DRUPAL_NODE_TAG=1.0-2.0.0
MEMCACHED_TAG=1-2.12.0
OPENSMTPD_TAG=6-1.13.0
RSYSLOG_TAG=latest
SELENIUM_CHROME_TAG=3.141
WEBGRIND_TAG=1-1.27.0
XHPROF_TAG=3.5.0
ZOOKEEPER_TAG=3.8
```

**Comment by donchi4all** [comment]
[env.txt](https://github.com/linnovate/openideal/files/8555743/env.txt)
Above is the text file format

@heyyo-droid

**Comment by heyyo-droid** [comment]
Pay attention to DB variables:

It should be:
```
DB_NAME=openideal
DB_USER=drupal
DB_PASSWORD=drupal
DB_ROOT_PASSWORD=password
DB_HOST=mariadb
DB_PORT=3306
DB_DRIVER=mysql
```

**Comment by donchi4all** [comment]
The same error  @heyyo-droid 
after
drush si -y --account-name admin --account-pass 1234 --account-mail donchi@example.com --site-name "Openidea L" --db-url=mysql://drupal:drupal@mariadb/openideal idea

**Comment by heyyo-droid** [comment]
If you added a settings.php please remove it before running drush si...

**Comment by donchi4all** [comment]
Thanks. I deleted settings.php and it works

**Comment by heyyo-droid** [comment]
I suppose you didn't restart the docker container after fixing .env(missing `DB_USER=drupal`).  
Just run again `make`

**Comment by donchi4all** [comment]
I need. I even deleted the container and started afresh.  Thanks so much @heyyo-droid
