### ISSUE TITLE
CSS  not loading

### ISSUE THREAD

**Issue by donchi4all** [linnovate/openideal#206]
<img width="1680" alt="Screenshot 2022-06-02 at 12 48 29" src="https://user-images.githubusercontent.com/33794017/171622844-857da55d-475d-48c4-89a0-7313eb1a17f0.png">
<img width="1675" alt="Screenshot 2022-06-02 at 12 48 56" src="https://user-images.githubusercontent.com/33794017/171622966-75052328-72fd-4572-b410-66bf8ac040c7.png">

@zohar @eyalev @konforti @israeldahan @heyyo-droid 

Kindly help

**Comment by donchi4all** [comment]
@heyyo-droid any help

**Comment by heyyo-droid** [comment]
@donchi4all did you follow this guide ?  Look at 6.

https://github.com/linnovate/openideal/wiki/Install-OpenideaL-with-Docker4Drupal-by-Wodby

**Comment by heyyo-droid** [comment]
`chown -R wodby:www-data sites/default/files`
`drush cr`
