### ISSUE TITLE
Install problem, while running '../vendor '....

### ISSUE THREAD

**Issue by edwardAGE4** [linnovate/openideal#207]
In ModuleInstaller.php line 91:

  Unable to install modules: module 'unlimited_number' is incompatible with this version of Drupal core.

**Comment by KomalAgarwal1** [comment]
Hi @edwardAGE4 

While trying to install the setup I am facing the same issue. Did you get the resolution for this problem?

**Comment by heyyo-droid** [comment]
Hi guys,
The last version of unlimited_number module removed support for Drupal 8.
Please try to reinstall the project tag 3.0.9.4, you shouldn't see this error anymore.

Regards

**Comment by KomalAgarwal1** [comment]
@heyyo-droid   

Can you please help me understand in which file this tag value has to be updated?

**Comment by heyyo-droid** [comment]
Just reinstall the project by following guide: https://github.com/linnovate/openideal/wiki/Install-OpenideaL-with-Docker4Drupal-by-Wodby

**Comment by KomalAgarwal1** [comment]
@heyyo-droid  I did that and landed to this issue

https://github.com/linnovate/openideal/issues/209

**Comment by heyyo-droid** [comment]
issue fixed since tag 3.0.9.4
