### ISSUE TITLE
French version

### ISSUE THREAD

**Issue by edwardAGE4** [linnovate/openideal#208]
Good Morning, do we have a pluggin or is it a possibility to change the language of the app to french ?

**Comment by heyyo-droid** [comment]
Bonjour Edouard,
OpenIdeal n'a pas été spécifiquement traduit pour la langue français.
Mais vous pouvez passer ce paramètre `--local=fr` lors de l'installation avec `drush si ...`.
Vous obtiendrez une installation avec les traductions françaises de Drupal core et des modules contrib.

**Comment by heyyo-droid** [comment]
Nous sommes ouverts bien entendu a toute contribution, si vous souhaitez participer a la localisation d'OpenIdeal

**Comment by heyyo-droid** [comment]
Je ferme cette issue, n'hesitez pas la reouvrir si vous avez besoin de plus amples informations
