### ISSUE TITLE
Design Error with Drupal from Docker

### ISSUE THREAD

**Issue by tbludau** [linnovate/openideal#54]
The OpenIdeaL extention has a very strange graphical overview, when installing on a fresh Drupal, which is deployed over a docker container. I used the Web-Interface for every module-installation and enablement.

![image](https://user-images.githubusercontent.com/16623209/35302069-93dbd854-008d-11e8-86c0-2258d0bc51bb.png)

This failure can be reproduced within 15 minutes.

docker run --name demodrupal -p 192.168.4.11:81:80 -d drupal:7
SQLite Installation

Installation Module:
https://www.drupal.org/project/idea/
 -> https://www.drupal.org/project/idea/releases/7.x-4.4
   -> https://ftp.drupal.org/files/projects/idea-7.x-4.4-no-core.zip

Enable following modules in the Web modules section:
Panels bootstrap layouts builder
Panels Bootstrap Layouts
Views Boostrap

Update Packages (view_bootstraps)
Update Database Scheme (Run database updates)

Add following modules in the Web modules section:

fe_default
fe_idea
fe_pages

Following failure:
![image](https://user-images.githubusercontent.com/16623209/35302019-768d62ae-008d-11e8-8bd6-17a08f975bf5.png)
Notice: Undefined property: stdClass::$insert_at_front in nodequeue_save() (line 1008 of /var/www/html/sites/all/modules/idea/modules/contrib/nodequeue/nodequeue.module).
Notice: Undefined property: stdClass::$insert_at_front in nodequeue_save() (line 1008 of /var/www/html/sites/all/modules/idea/modules/contrib/nodequeue/nodequeue.module).

Add content
 -> Add new content
   -> Idea (Save)

http://192.168.4.11:81/ideas
(No Content)

Add following Module in the web modules section (with dependencies):
fe_news

Ideas:
![image](https://user-images.githubusercontent.com/16623209/35302069-93dbd854-008d-11e8-86c0-2258d0bc51bb.png)

**Comment by zohar** [comment]
@tbludau It seems that you didn't run the installation properly. 
I'm not sure you built the project before installing it.

After pulling the repository, run `drush make openideal-github.make` to build the project, and only then run the installation. 

This has been tested many times without any error. I'm closing for now. Re-open if you ran the steps above and still getting errors.
