### ISSUE TITLE
management graphs dont work in disconnected "onprem" environments

### ISSUE THREAD

**Issue by liorkesos** [linnovate/openideal#55]
Google charts which we use for the statistics dont work in disconnected systems.
See this for details...
https://developers.google.com/chart/interactive/faq

> Can I use charts offline?
Your users' computers must have access to https://www.gstatic.com/charts/loader.js in order to use the interactive features of Google Charts. This is because the visualization libraries that your page requires are loaded dynamically before you use them. The code for loading the appropriate library is part of the included script, and is called when you invoke the google.charts.load() method. Our terms of service do not allow you to download the google.charts.load or google.visualization code to use offline.
Can I download and host the chart code locally, or on an intranet?
Sorry; our terms of service do not allow you to download and save or host the google.charts.load or google.visualization code. However, if you don't need the interactivity of Google Charts, you can screenshot the charts and use them as you wish.

**Comment by zohar** [comment]
See #36 - Moving to D3 instead of Google charts.
