### ISSUE TITLE
Bug on content type news ?

### ISSUE THREAD

**Issue by dbourrion** [linnovate/openideal#56]
Hi
After two fresh install on two different computer, I can see something is rong with content type "news" that appears as חדשות (Machine name: news) in the baskoffice.
Trying to add a new content חדשות (Machine name: news) give's an error.
The log is : 

> Error: Call to undefined function i18n_taxonomy_allowed_values() in taxonomy_options_list() (line 1496 of /var/www/html/openideal/modules/taxonomy/taxonomy.module).

**Comment by dbourrion** [comment]
Hi
Downloading and enabling Taxonomy translation (i18n_taxonomy) via https://www.drupal.org/project/i18n fixed that.
Closing.

**Comment by dbourrion** [comment]
Inspiration to fix that has come wehn reading that https://www.drupal.org/project/features/issues/2505505#comment-10023253

**Comment by dbourrion** [comment]
Hum.... But enabling i18n_taxonomy crashes the message that are used in the "latest and greatest" zone, and also those in "Activity"....

**Comment by zohar** [comment]
Hi @dbourrion - thanks for spotting this one up. 
Having חדשות in the code is wrong anyway. The code should contain only English characters. 
I'd happily accept a patch for this (replacing all `חדשות` with `News`)

**Comment by dbourrion** [comment]
Well, one can change this directly in the content types  (replacing all חדשות with News)
The real problem I see is that enabling i18n_* makes all the messages disappearing ; that a real problem...

**Comment by zohar** [comment]
It should be changed directly in code actually, by running a suitable search-and-replace.

**Comment by dbourrion** [comment]
Well, I've try to find the 'חדשות" occurrences with regexxer and grep after having cloned the repository.
Can't find any.. I must missing someting...

**Comment by dbourrion** [comment]
`daniel@daniel-iMac:~/ownCloud/openideal$` grep -rl 'חדשות'
`daniel@daniel-iMac:~/ownCloud/openideal$` grep -rl 'News'
`libraries/modernizr/test/js/lib/uaparser.js`
`libraries/backbone/index.html`
`modules/features/fe_news/fe_news.features.inc`
`modules/features/fe_news/fe_news.features.taxonomy.inc`
`modules/features/fe_news/fe_news.info`
`modules/features/fe_news/fe_news.features.field_instance.inc`
`modules/features/fe_news/fe_news.features.field.inc`
`modules/features/fe_news/fe_news.views_default.inc`
`idea.profile`
`daniel@daniel-iMac:~/ownCloud/openideal$` grep -rl 'חדשות'

**Comment by dbourrion** [comment]
Well, I'm not familiar with git etc. Trying to make a push from GitKraken, it fails. So let's do it this way : the prob is in modules/features/fe_news/fe_news.features.inc line 32 and modules/features/fe_news/fe_news.views_default.inc line 25

**Comment by dbourrion** [comment]
(ok, it looks I don't have rights to push something, I understand that now)

**Comment by zohar** [comment]
https://github.com/linnovate/openideal/commit/0ebeff8df7438aa9124b03c69bbb70bdcb1eaafc

**Comment by zohar** [comment]
@dbourrion you can fork this repository to your own space, modify the code, then create a pull request (for further changes you may suggest). See https://help.github.com/articles/about-forks/

**Comment by dbourrion** [comment]
Well, I've a lot to learn with Git. Gonna do that before playing here ;)

**Comment by zohar** [comment]
Fixed in https://github.com/linnovate/openideal/commit/0ebeff8df7438aa9124b03c69bbb70bdcb1eaafc
