### ISSUE TITLE
Errors during and after installation

### ISSUE THREAD

**Issue by RichStone** [linnovate/openideal#59]
## Installation on
_________
 
Ubuntu 16.04
drush version 5.10.0
mysql: mysqladmin  Ver 8.42 Distrib 5.7.23, for Linux on x86_64
_________

I got some errors after installation immediately:
![conf](https://user-images.githubusercontent.com/15954169/44530075-e852ca80-a6ed-11e8-904e-023a84b56ff0.png)

and a few others in the GUI:
![ideas](https://user-images.githubusercontent.com/15954169/44530101-f9034080-a6ed-11e8-94d9-dc2f52868343.png)
![challenges](https://user-images.githubusercontent.com/15954169/44530114-fef92180-a6ed-11e8-85fb-52f9a4419ec0.png)

What could be wrong?

**Comment by zohar** [comment]
Your installation clearly failed. The GUI is not the OpenideaL one (except for the theme of the installation screen).
How did you try to install it?

**Comment by RichStone** [comment]
hey @zohar!
These were my steps:
```
# download the project from github in an openideal folder in my home directory
cd openideal
drush make build-openideal-github.make /home/cqtn/www/html
# drush make runs through perfectly

cd  /home/cqtn/www/html
sudo chmod 777 -R sites/
cd sites/default/
cp default.settings.php settings.php
sudo chmod 777 settings.php
``` 
Then heading over to my localhost I pass through the Welcome and Verify Requirements steps. When I tried the installation today, there would be no visible progress in the installation but this error message:
![bildschirmfoto vom 2018-08-28 10-07-33](https://user-images.githubusercontent.com/15954169/44709612-56124400-aaaa-11e8-97dd-e76f54cbe096.png)

But something gets still installed, although way less than last week:
![bildschirmfoto vom 2018-08-28 10-07-59](https://user-images.githubusercontent.com/15954169/44709760-b0aba000-aaaa-11e8-87f2-b63669bca82b.png)

So this happens with an existing database.

If I delete the db and reinstall, I see progress again and the installation is more complete, but I still get during installation:
![bildschirmfoto vom 2018-08-28 10-24-19](https://user-images.githubusercontent.com/15954169/44710517-9672c180-aaac-11e8-9504-f82e0b39562c.png)

The MySQL database on my local machine looks quite good, filled with tables and values.

**Comment by RichStone** [comment]
This last installation of mine ended like this:
![bildschirmfoto vom 2018-08-28 10-26-45](https://user-images.githubusercontent.com/15954169/44710724-126d0980-aaad-11e8-82b2-b01b784e62a0.png)
(the error link to the "error page" show nothing)

![bildschirmfoto vom 2018-08-28 10-27-40](https://user-images.githubusercontent.com/15954169/44710727-1305a000-aaad-11e8-9cb9-3070a91b23a0.png)

**Comment by zohar** [comment]
I can't tell from the above errors what goes wrong in your installation. I didn't experience any of these.
:-(

**Comment by zohar** [comment]
Unless other people run into the same problem, you can get punctual professional help from Linnovate if you'd like... contact via contact@linnovate.net
